/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OpikApi from "../../../../api/index";
import * as core from "../../../../core";

export const ProjectUpdateVisibility: core.serialization.Schema<
    serializers.ProjectUpdateVisibility.Raw,
    OpikApi.ProjectUpdateVisibility
> = core.serialization.enum_(["private", "public"]);

export declare namespace ProjectUpdateVisibility {
    export type Raw = "private" | "public";
}
