// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ProjectMetricRequestPublicInterval: core.serialization.Schema<
    serializers.ProjectMetricRequestPublicInterval.Raw,
    OpikApi.ProjectMetricRequestPublicInterval
> = core.serialization.enum_(["HOURLY", "DAILY", "WEEKLY"]);

export declare namespace ProjectMetricRequestPublicInterval {
    export type Raw = "HOURLY" | "DAILY" | "WEEKLY";
}
