/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProjectWriteVisibility = "private" | "public";
export const ProjectWriteVisibility = {
    Private: "private",
    Public: "public",
} as const;
