{{- if and .Values.caCerts.additionalCACerts (not .Values.caCerts.existingAdditionalCACertsRef) (not .Values.caCerts.overwriteJavaCATrustStore.enabled) }}
apiVersion: v1
kind: {{ ternary "Secret" "ConfigMap" .Values.caCerts.additionalCACertsInSecret }}
metadata:
  name: {{ include "opik.name" $ }}-extra-ca-certs
  {{- if .Values.caCerts.additionalCACertsInSecret }}
type: Opaque
  {{- end }}
data:
  {{- range .Values.caCerts.additionalCACerts }}
  {{ .name }}.pem: |
    {{- if .Values.caCerts.additionalCACertsInSecret }}
    {{ .content | b64enc | indent 4 }}
    {{- else }}
    {{ .content | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
