{{- if .Values.chartMigration.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opik.fullname" . }}-chart-migration-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.global.argocd }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-15"
    {{- else }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "opik.fullname" . }}-chart-migration-role
  namespace: {{ .Release.Namespace }}
  annotations:
   {{- if .Values.global.argocd }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-15"
    {{- else }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "opik.fullname" . }}-chart-migration-rb
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.global.argocd }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-15"
    {{- else }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "opik.fullname" . }}-chart-migration-role
subjects:
  - kind: ServiceAccount
    name: {{ include "opik.fullname" . }}-chart-migration-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "opik.fullname" . }}-chart-migration
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opik.labels" $  | nindent 4 }}
    component: {{ include "opik.name" $ }}-chart-migration
    {{- with $.Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}  
  annotations:
    {{- if .Values.global.argocd }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-10"
    {{- else }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: pre-upgrade-cleanup
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.chartMigration.serviceAccountName | default (printf "%s-chart-migration-sa" (include "opik.fullname" .)) }}
      {{- with (.Values.chartMigration.nodeSelector | default .Values.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.chartMigration.tolerations | default .Values.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migration
          image: {{ .Values.chartMigration.image }}
          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "=== Pre-Upgrade Chart Migration ==="
              NAMESPACE="{{ .Release.Namespace }}"
              COMPONENTS_REMOVED=0

              # --- Helper functions ---
              is_bitnami() {
                kubectl get statefulset "$1" -n $NAMESPACE -o jsonpath='{.spec.template.spec.containers[*].image}' 2>/dev/null | grep -q "bitnami"
              }

              has_wrong_zk_selector() {
                local SEL=$(kubectl get statefulset "$1" -n $NAMESPACE -o jsonpath='{.spec.selector.matchLabels.app\.kubernetes\.io/name}' 2>/dev/null || echo "")
                [ "$SEL" = "zookeeper" ] && [ "$1" != "$2" ]
              }

              has_missing_vct_labels() {
                local LABELS=$(kubectl get statefulset "$1" -n $NAMESPACE -o jsonpath='{.spec.volumeClaimTemplates[0].metadata.labels}' 2>/dev/null || echo "")
                kubectl get statefulset "$1" -n $NAMESPACE 2>/dev/null && [ -z "$LABELS" ]
              }

              delete_sts() {
                echo "Deleting StatefulSet $1..."
                kubectl delete statefulset "$1" -n $NAMESPACE --wait=true
                echo "StatefulSet $1 deleted"
                COMPONENTS_REMOVED=$((COMPONENTS_REMOVED + 1))
              }

              delete_deployment() {
                if kubectl get deployment "$1" -n $NAMESPACE 2>/dev/null; then
                  echo "Deleting deployment $1..."
                  kubectl delete deployment "$1" -n $NAMESPACE --wait=true
                  echo "Deployment $1 deleted"
                else
                  echo "Deployment $1 not found, skipping"
                fi
              }

              # --- MySQL ---
              {{- if .Values.mysql.enabled }}
              MYSQL_STS="{{ .Values.mysql.fullnameOverride | default "opik-mysql" }}"
              echo "Checking MySQL: $MYSQL_STS"
              if is_bitnami "$MYSQL_STS"; then
                delete_sts "$MYSQL_STS"
              else
                echo "Skipping $MYSQL_STS"
              fi
              echo ""
              {{- end }}

              # --- Zookeeper ---
              {{- if .Values.zookeeper.enabled }}
              ZK_STS="{{ .Values.zookeeper.fullnameOverride | default "opik-zookeeper" }}"
              echo "Checking Zookeeper: $ZK_STS"
              if is_bitnami "$ZK_STS" || has_wrong_zk_selector "$ZK_STS" "zookeeper-opik"; then
                delete_sts "$ZK_STS"
              else
                echo "Skipping $ZK_STS"
              fi
              echo ""
              {{- end }}

              # --- Redis ---
              {{- if .Values.redis.enabled }}
              REDIS_STS="{{ .Values.redis.fullnameOverride | default "opik-redis-master" }}"
              echo "Checking Redis: $REDIS_STS"
              if is_bitnami "$REDIS_STS" || has_missing_vct_labels "$REDIS_STS"; then
                delete_sts "$REDIS_STS"
              else
                echo "Skipping $REDIS_STS"
              fi
              echo ""
              {{- end }}

              # --- Delete backend deployment if any components were removed ---
              if [ $COMPONENTS_REMOVED -gt 0 ]; then
                echo "Components removed: $COMPONENTS_REMOVED. Deleting backend deployment..."
                delete_deployment "{{ include "opik.name" . }}-backend"
              else
                echo "No components removed, skipping backend deployment deletion"
              fi

              echo "=== Migration Completed Successfully ==="

{{- end }}

