
{{- if and .Values.clickhouse.enabled .Values.clickhouse.monitoring.enabled  }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opik.name" $ }}-ch-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "altinity-clickhouse-operator.labels" . | nindent 4 }}
    {{- include "opik.clickhouse.labels" . | nindent 4 }}
    {{- with .Values.clickhouse.monitoring.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    service-name: {{ include "opik.name" $ }}-ch-monitoring
  {{- with .annotations }}
  annotations:
    {{- with .Values.clickhouse.monitoring.annotations  }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.clickhouse.monitoring.service.type }}
  selector:
    {{- include "opik.clickhouse.selectorLabels" . | nindent 4 }}
  ports:
  {{- range .Values.clickhouse.monitoring.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default "9363" }}
      protocol: {{ .protocol | default "TCP"}}
      name: {{ .name | default "prometheus-metrics" }}
    {{- end }}
{{- end }}

####################################

{{- if and .Values.clickhouse.enabled .Values.clickhouse.backupServer.enabled .Values.clickhouse.backupServer.monitoring.enabled  }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opik.name" $ }}-ch-backup-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "altinity-clickhouse-operator.labels" . | nindent 4 }}
    {{- include "opik.clickhouse.labels" . | nindent 4 }}
    {{- with .Values.clickhouse.backupServer.monitoring.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    service-name: {{ include "opik.name" $ }}-ch-backup-monitoring
  {{- with .annotations }}
  annotations:
    {{- with .Values.clickhouse.backupServer.monitoring.annotations  }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.clickhouse.backupServer.monitoring.service.type }}
  selector:
    {{- include "opik.clickhouse.selectorLabels" . | nindent 4 }}
  ports:
  {{- range .Values.clickhouse.backupServer.monitoring.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default "7171" }}
      protocol: {{ .protocol | default "TCP"}}
      name: {{ .name | default "ch-backup-rest" }}
    {{- end }}
{{- end }}
