{{ if and .Values.clickhouse.enabled .Values.clickhouse.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "opik.name" $ }}-clickhouse-backup
spec:
  schedule: "{{ .Values.clickhouse.backup.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.clickhouse.backup.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: clickhouse-backup
            {{- with .Values.commonLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- if .Values.clickhouse.backup.serviceAccount.enabled }}
          serviceAccountName: {{ .Values.clickhouse.backup.serviceAccount.name | default "clickhouse-backup" }}
          {{- end }}
          containers:
          - name: clickhouse-backup-job
            image: {{ .Values.clickhouse.image }}
            {{- with .Values.clickhouse.imagePullSecrets }}
            imagePullSecrets:
              {{- toYaml . | nindent 8 }}
            {{- end }}
            command:
              - "/bin/bash"
              - "-c"
            args:
              - export backupname=backup$(date +'%Y%m%d%H%M'); echo "BACKUP ALL EXCEPT DATABASE system TO S3('{{ include "common.tplvalues.render" (dict "value" .Values.clickhouse.backup.bucketURL "context" $) }}/$backupname/', '$ACCESS_KEY', '$SECRET_KEY');" > /tmp/backQuery.sql; clickhouse-client -h clickhouse-opik-clickhouse --send_timeout 600000 --receive_timeout 600000 --port 9000 --queries-file=/tmp/backQuery.sql;
            {{- with .Values.clickhouse.backup.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            env:
            - name: CLICKHOUSE_USER
              value: {{ .Values.clickhouse.adminUser.username }}
            - name: CLICKHOUSE_PASSWORD
            {{- if .Values.clickhouse.adminUser.useSecret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "opik.name" .}}-{{ .Values.clickhouse.adminUser.secretname }}
                  key: {{ .Values.clickhouse.adminUser.password_key }}
            {{- else }}
              value: {{ .Values.clickhouse.adminUser.password }}
            {{- end }}
            {{- if not .Values.clickhouse.backup.serviceAccount.enabled }}
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.clickhouse.backup.secretName}}
                  key: {{ .Values.clickhouse.backup.accessKey | default "access_key_id" }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.clickhouse.backup.secretName}}
                  key: {{ .Values.clickhouse.backup.secretKey | default "access_key_secret" }}
            {{- else }}
            - name: ACCESS_KEY
              value: ""
            - name: SECRET_KEY
              value: ""
            {{- end }}

          {{- with .Values.clickhouse.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.clickhouse.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
      backoffLimit:
{{end}}
