apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: {{ include "opik.name" $ }}-clickhouse
  namespace: {{ .Release.namespace }}
  labels:
    component: clickhouse
    {{- include "opik.labels" $  | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  defaults:
    templates:
      podTemplate: clickhouse-cluster-pod-template
      serviceTemplate: {{ .Values.clickhouse.service.serviceTemplate }}
      volumeClaimTemplate: storage-vc-template
  configuration:
    users:
      {{- if .Values.clickhouse.adminUser.useSecret.enabled }}
      {{ .Values.clickhouse.adminUser.username }}/k8s_secret_password: {{ include "opik.name" .}}-{{ .Values.clickhouse.adminUser.secretname }}/{{ .Values.clickhouse.adminUser.password_key }}
      {{- else }}
      {{ .Values.clickhouse.adminUser.username }}/password: {{ .Values.clickhouse.adminUser.password }}
      {{- end }}
      {{ .Values.clickhouse.adminUser.username }}/access_management: 1
      {{ .Values.clickhouse.adminUser.username }}/networks/ip:
        - '127.0.0.1/32'
        - '0.0.0.0/0'
      {{- if .Values.clickhouse.monitoring.enabled }}
      {{- if .Values.clickhouse.monitoring.useSecret.enabled }}
      {{ .Values.clickhouse.monitoring.username }}/k8s_secret_password: {{ include "opik.name" .}}-{{ .Values.clickhouse.monitoring.secretname }}/{{ .Values.clickhouse.monitoring.password_key }}
      {{- else }}
      {{ .Values.clickhouse.monitoring.username }}/password: {{ .Values.clickhouse.monitoring.password }}
      {{- end }}
      {{ .Values.clickhouse.monitoring.username }}/networks/ip:
        - '127.0.0.1/32'
        - '0.0.0.0/0'
      {{- end }}
    {{- if .Values.clickhouse.monitoring.enabled }}
    profiles:
      {{ .Values.clickhouse.monitoring.username }}/readonly: 1
    {{- end }}

    {{- if .Values.zookeeper.enabled }}
    zookeeper:
        nodes:
        - host: {{ .Values.clickhouse.zookeeper.host }}
          port: 2181
    {{- end }}
    clusters:
      - name: cluster
        layout:
          shardsCount: {{ .Values.clickhouse.shardsCount }}
          replicasCount: {{ .Values.clickhouse.replicasCount }}
        templates:
          podTemplate: clickhouse-cluster-pod-template
          serviceTemplate: {{ .Values.clickhouse.service.serviceTemplate }}
          volumeClaimTemplate: storage-vc-template
  templates:
    podTemplates:
      - name: clickhouse-cluster-pod-template
        spec:
          containers:
          - name: clickhouse
            image: {{ .Values.clickhouse.image }}
            {{- with .Values.clickhouse.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}

          {{- with .Values.clickhouse.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.clickhouse.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- with .Values.clickhouse.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}

    serviceTemplates:
      - name: clickhouse-cluster-svc-lb-template
        metadata:
          annotations:
            {{- with .Values.clickhouse.service.annotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          ports:
            - name: http
              port: 8123
              targetPort: 8123
            - name: tcp
              port: 9000
              targetPort: 9000
          type: LoadBalancer      

    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          {{- if .Values.clickhouse.storageClassName }}
          storageClassName:  {{ .Values.clickhouse.storageClassName }}
          {{- end }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouse.storage }}    
