{{- if (index .Values "oauth2-proxy" "enabled") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opik.fullname" . }}-oauth2-ingress
  labels:
    {{- include "opik.labels" . | nindent 4 }}
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
spec:
  ingressClassName: azure-application-gateway
  tls:
    - secretName: opik-tls-secret
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "opik.fullname" . }}-oauth2-proxy
                port:
                  number: {{ (index .Values "oauth2-proxy" "service" "portNumber") }}
{{- end }}
