{{- if and (index .Values "oauth2-proxy" "enabled") (not .Values.disableOAuth2Ingress) }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opik.fullname" . }}-oauth2-ingress
  labels:
    {{- include "opik.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.ingressClassName "nginx" }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "http"
    {{- else }}
    appgw.ingress.kubernetes.io/ssl-redirect: "false"
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
    {{- end }}
    {{- if and .Values.ssl.enabled .Values.ssl.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ssl.issuer | quote }}
    cert-manager.io/acme-challenge-type: "http01"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "azure-application-gateway" }}
  tls:
    - secretName: opik-tls-secret
      {{- if .Values.ssl.hosts }}
      hosts:
        {{- range .Values.ssl.hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
  rules:
    {{- if .Values.ssl.hosts }}
    {{- range .Values.ssl.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "opik.fullname" $ }}-oauth2-proxy
                port:
                  number: {{ (index $.Values "oauth2-proxy" "service" "portNumber") }}
    {{- end }}
    {{- else }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "opik.fullname" . }}-oauth2-proxy
                port:
                  number: {{ (index .Values "oauth2-proxy" "service" "portNumber") }}
    {{- end }}
{{- end }}
{{- end }}
