{{- if index .Values "oauth2-proxy" "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opik-nginx-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opik-nginx-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: opik-nginx-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opik-nginx-proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: nginx-config
        configMap:
          name: opik-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: opik-nginx-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opik-nginx-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: opik-nginx-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
