{{- if .Values.secretStore.enabled }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecretsStoreRef.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opik.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region }}
      role: {{ .Values.secretStore.role }}
{{- end }}
