{{- range $key, $value := .Values.component }}
{{- if $value.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opik.name" $ }}-{{ $key | lower }}
  labels:
    {{- include "opik.labels" $  | nindent 4 }}
    component: {{ include "opik.name" $ }}-{{ $key | lower }}
  {{- if $value.service.annotations }}
  annotations:
    {{- with $value.service.annotations | default "" }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ $value.service.type }}
  selector:
    component: {{ include "opik.name" $ }}-{{ $key | lower }}
  ports:
  {{- range $value.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
{{- end }}
{{- end }}
