{{- range $key, $value := .Values.component }}
{{- if and $value.enabled $value.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opik.name" $ }}-{{ $key | lower }}
  labels:
    {{- include "opik.labels" $ | nindent 4 }}
  {{- with $value.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}