{{- range $key, $value := .Values.component }}
{{- if $value.metrics.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "opik.name" $ }}-{{ $key | lower }}
  namespace: {{ default $.Release.Namespace $value.metrics.namespace | quote }}
  labels:
    {{- include "opik.labels" $  | nindent 4 }}
    component: {{ include "opik.name" $ }}-{{ $key | lower }}
    {{- with $value.metrics.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $.Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- if $value.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" $value.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: {{ $value.metrics.portName | default "http" }}
      {{- if $value.metrics.interval }}
      interval: {{ $value.metrics.interval | default "60s" | quote}}
      {{- end }}
      {{- if $value.metrics.scrapeTimeout }}
      scrapeTimeout: {{ $value.metrics.scrapeTimeout }}
      {{- end }}
      {{- if $value.metrics.honorLabels }}
      honorLabels: {{ $value.metrics.honorLabels }}
      {{- end }}
      {{- if $value.metrics.relabelings }}
      relabelings: {{- toYaml $value.metrics.relabelings | nindent 6 }}
      {{- end }}
      {{- if $value.metrics.metricRelabelings }}
      metricRelabelings: {{- toYaml $value.metrics.metricRelabelings | nindent 6 }}
      {{- end }}
      {{- if $value.metrics.path }}
      path: {{ $value.metrics.path }}
      {{- end }}
  {{- if $value.metrics.podTargetLabels }}
  podTargetLabels: {{- toYaml $value.metrics.podTargetLabels | nindent 4 }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ default $.Release.Namespace $value.metrics.namespace | quote }}
  selector:
    matchLabels:
      {{- include "opik.labels" $  | nindent 6 }}
      component: {{ include "opik.name" $ }}-{{ $key | lower }}
{{- end }}
{{- end }}
