{{- range $key, $value := .Values.component }}
{{- if and $value.enabled $value.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.serviceAccountName" . }}
  labels:
  {{- include "opik.labels" $ | nindent 4 }}
  {{- with $value.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

{{- if and .Values.clickhouse.enabled .Values.clickhouse.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickhouse.serviceAccountName" . }}
  labels:
    {{- include "opik.labels" $ | nindent 4 }}
  {{- with .Values.clickhouse.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if and .Values.clickhouse.enabled .Values.clickhouse.backup.enabled .Values.clickhouse.backup.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickhouse.backup.serviceAccountName" . }}
  labels:
    {{- include "opik.labels" $ | nindent 4 }}
  {{- with .Values.clickhouse.backup.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opik.serviceAccountName" . }}
  labels:
    {{- include "opik.labels" $ | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
