{{- if (index .Values "oauth2-proxy" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: opik-tls-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opik.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  # These will be populated by the deployment script
  tls.crt: ""
  tls.key: ""
{{- end }}
