"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PromptVersionRetrieveDetail = exports.PromptUpdatable = exports.CreatePromptVersionDetail = exports.PromptWrite = void 0;
var PromptWrite_1 = require("./PromptWrite");
Object.defineProperty(exports, "PromptWrite", { enumerable: true, get: function () { return PromptWrite_1.PromptWrite; } });
var CreatePromptVersionDetail_1 = require("./CreatePromptVersionDetail");
Object.defineProperty(exports, "CreatePromptVersionDetail", { enumerable: true, get: function () { return CreatePromptVersionDetail_1.CreatePromptVersionDetail; } });
var PromptUpdatable_1 = require("./PromptUpdatable");
Object.defineProperty(exports, "PromptUpdatable", { enumerable: true, get: function () { return PromptUpdatable_1.PromptUpdatable; } });
var PromptVersionRetrieveDetail_1 = require("./PromptVersionRetrieveDetail");
Object.defineProperty(exports, "PromptVersionRetrieveDetail", { enumerable: true, get: function () { return PromptVersionRetrieveDetail_1.PromptVersionRetrieveDetail; } });
