// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const PromptVersionEnvironmentUpdate: core.serialization.Schema<
    serializers.PromptVersionEnvironmentUpdate.Raw,
    OpikApi.PromptVersionEnvironmentUpdate
> = core.serialization.object({
    environments: core.serialization.list(core.serialization.string()),
});

export declare namespace PromptVersionEnvironmentUpdate {
    export interface Raw {
        environments: string[];
    }
}
