Frontend:
  - changed-files:
    - any-glob-to-any-file: 'apps/opik-frontend/**/*'

Backend:
  - changed-files:
    - any-glob-to-any-file: 'apps/opik-backend/**/*'

Python SDK:
  - changed-files:
    - any-glob-to-any-file: 'sdks/python/**/*'

TypeScript SDK:
  - changed-files:
    - any-glob-to-any-file: 'sdks/typescript/**/*'

Infrastructure:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'deployment/**/*'
      - 'scripts/**/*'
      - 'extensions/**/*'
      - '*.sh'
      - '*.ps1'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'apps/opik-documentation/**/*'
      - '**/*.md'
      - '**/*.mdx'
