// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface FindFeedbackDefinitionsRequest {
    page?: number;
    size?: number;
    name?: string;
    type?: OpikApi.FindFeedbackDefinitionsRequestType;
}
