---
repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: helm-docs
        language: docker_image
        entry: jnorwood/helm-docs:v1.14.2
        args:
          - --chart-search-root=deployment/helm_chart/opik
        files: (README\.md\.gotmpl|values\.yaml|Chart\.yaml)$
        pass_filenames: false

...
