enabled: true
serviceAccount:
  create: true
  name: opik-frontend
metrics:
  enabled: false
image:
  repository: opik-frontend
  pullPolicy: IfNotPresent
  tag: latest
replicaCount: 1
autoscaling:
  enabled: false
backendConfigMap:
  enabled: false
resources:
  requests:
    ephemeral-storage: 10Gi
volumeMounts:
  - mountPath: /etc/nginx/conf.d/
    name: opik-frontend-nginx
volumes:
  - name: opik-frontend-nginx
    configMap:
      name: opik-frontend-nginx
      items:
        - key: default.conf
          path: default.conf
service:
  type: ClusterIP
  ports:
    - name: http
      port: 5173
      protocol: TCP
      targetPort: 5173
ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  hosts: []
  # - host: opik.example.com
  #   paths:
  #     - path: /
  #       port: 5173
  #       pathType: Prefix
  tls:
    enabled: false
    hosts: []
    secretName: ""
logFormats:
  logger-json: |-
    escape=json '{'
            '  "body_bytes_sent": $body_bytes_sent'
            ', "comet_workspace": "$http_comet_workspace"'
            ', "host": "$host"'
            ', "http_referer": "$http_referer"'
            ', "http_user_agent": "$http_user_agent"'
            ', "limit_req_status": "$limit_req_status"'
            ', "method": "$request_method"'
            ', "remote_addr": "$remote_addr"'
            ', "remote_user": "$remote_user"'
            ', "request_length": $request_length'
            ', "request_time": $request_time'
            ', "request": "$request"'
            ', "response": $status'
            ', "resp_body_size": $body_bytes_sent'
            ', "source": "nginx"'
            ', "status": $status'
            ', "time_local": "$time_local"'
            ', "time": $msec'
            ', "uri": "$request_uri"'
            ', "user_agent": "$http_user_agent"'
            ', "x_forwarded_for": "$http_x_forwarded_for"'
            ', "x_sdk_version": "$http_x_opik_debug_sdk_version"'
            ', "upstream_connect_time": "$upstream_connect_time", "upstream_header_time": "$upstream_header_time", "upstream_response_time": "$upstream_response_time"'
            ', "upstream_addr": "$upstream_addr", "upstream_status": "$upstream_status", "host": "$host"'
        '}'
# throttled locations
throttling: {}
# map variables for use with throttling and other places
maps: []
# use internal aws resolvr on vpc
awsResolver: false
logFormat: logger-json
logFormats:
  "logger-json": >-
    escape=json '{ "body_bytes_sent": $body_bytes_sent, "http_referer": "$http_referer", "http_user_agent": "$http_user_agent", "remote_addr": "$remote_addr", "remote_user": "$remote_user", "request": "$request", "status": $status, "time_local": "$time_local", "x_forwarded_for": "$http_x_forwarded_for" }'
upstreamConfig: {}
# proxy_read_timeout: 60
# proxy_connect_timeout: 60
# proxy_send_timeout: 60
# proxy_buffering: 'on'
# proxy_request_buffering: 'on'
