enabled: true
serviceAccount:
  create: true
  name: opik-frontend
metrics:
  enabled: false
image:
  repository: opik-frontend
  pullPolicy: IfNotPresent
  tag: latest
replicaCount: 1
autoscaling:
  enabled: false
backendConfigMap:
  enabled: false
resources:
  requests:
    ephemeral-storage: 10Gi
service:
  type: ClusterIP
  ports:
    - name: http
      port: 5173
      protocol: TCP
      targetPort: 5173
ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  hosts: []
  # - host: opik.example.com
  #   paths:
  #     - path: /
  #       port: 5173
  #       pathType: Prefix
  tls:
    enabled: false
    hosts: []
    secretName: ""
# throttled locations
throttling: {}
# map variables for use with throttling and other places
maps: []
# use internal aws resolvr on vpc
awsResolver: false
# Enable HSTS header (only enable when running behind HTTPS termination)
hstsEnabled: false
upstreamConfig: {}
# proxy_read_timeout: 60
# proxy_connect_timeout: 60
# proxy_send_timeout: 60
# proxy_buffering: 'on'
# proxy_request_buffering: 'on'
podDisruptionBudget:
  enabled: false
