/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpikApi from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ProjectUpdate {
    name?: string;
    description?: string;
    visibility?: OpikApi.ProjectUpdateVisibility;
}
