---
# Model Configuration for End-to-End Playground Tests
# This file defines models that will be tested in playground tests
# To add a new model: just add it to the appropriate provider section below

providers:
  openai:
    display_name: "OpenAI"
    api_key_env_var: "OPENAI_API_KEY"
    models:
      - name: "GPT 4o"
        ui_selector: "GPT 4o"
        enabled: true
        test_playground: true
      - name: "GPT 4o Mini"
        ui_selector: "GPT 4o Mini"
        enabled: true
        test_playground: true
      - name: "GPT 4.1"
        ui_selector: "GPT 4.1"
        enabled: false
        test_playground: false
      - name: "GPT 4.1 Mini"
        ui_selector: "GPT 4.1 Mini"
        enabled: false
        test_playground: false

  anthropic:
    display_name: "Anthropic"
    api_key_env_var: "ANTHROPIC_API_KEY"
    models:
      - name: "Claude Opus 4.1"
        ui_selector: "Claude Opus 4.1"
        enabled: true
        test_playground: true
      - name: "Claude Sonnet 4.5"
        ui_selector: "Claude Sonnet 4.5"
        enabled: true
        test_playground: true
      - name: "Claude Sonnet 4"
        ui_selector: "Claude Sonnet 4"
        enabled: true
        test_playground: true
      - name: "Claude Haiku 4.5"
        ui_selector: "Claude Haiku 4.5"
        enabled: true
        test_playground: true
      - name: "Claude Haiku 3.5"
        ui_selector: "Claude Haiku 3.5"
        enabled: false
        test_playground: false
      - name: "Claude Sonnet 3.7"
        ui_selector: "Claude Sonnet 3.7"
        enabled: false
        test_playground: false

test_config:
  skip_missing_api_keys: true
  response_timeout: 30
  test_prompt: "Explain what is an LLM in one paragraph."
  only_test_enabled: true
