# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.analytics_query_response import AnalyticsQueryResponse
from .raw_client import AsyncRawSystemAnalyticsQueriesClient, RawSystemAnalyticsQueriesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SystemAnalyticsQueriesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSystemAnalyticsQueriesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSystemAnalyticsQueriesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSystemAnalyticsQueriesClient
        """
        return self._raw_client

    def execute_analytics_query(
        self, project_id: str, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AnalyticsQueryResponse:
        """
        Runs Ollie-generated read-only SQL bounded to the caller's workspace and the requested project. Returns 501 when the Agent Insights toggle is off.

        Parameters
        ----------
        project_id : str

        query : str
            Read-only ClickHouse SQL. Must return exactly one column named `result` produced via toJSONString(...)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnalyticsQueryResponse
            Query results

        Examples
        --------
        from Opik import OpikApi
        client = OpikApi(api_key="YOUR_API_KEY", workspace_name="YOUR_WORKSPACE_NAME", )
        client.system_analytics_queries.execute_analytics_query(project_id='projectId', query='query', )
        """
        _response = self._raw_client.execute_analytics_query(project_id, query=query, request_options=request_options)
        return _response.data


class AsyncSystemAnalyticsQueriesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSystemAnalyticsQueriesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSystemAnalyticsQueriesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSystemAnalyticsQueriesClient
        """
        return self._raw_client

    async def execute_analytics_query(
        self, project_id: str, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AnalyticsQueryResponse:
        """
        Runs Ollie-generated read-only SQL bounded to the caller's workspace and the requested project. Returns 501 when the Agent Insights toggle is off.

        Parameters
        ----------
        project_id : str

        query : str
            Read-only ClickHouse SQL. Must return exactly one column named `result` produced via toJSONString(...)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnalyticsQueryResponse
            Query results

        Examples
        --------
        from Opik import AsyncOpikApi
        import asyncio
        client = AsyncOpikApi(api_key="YOUR_API_KEY", workspace_name="YOUR_WORKSPACE_NAME", )
        async def main() -> None:
            await client.system_analytics_queries.execute_analytics_query(project_id='projectId', query='query', )
        asyncio.run(main())
        """
        _response = await self._raw_client.execute_analytics_query(
            project_id, query=query, request_options=request_options
        )
        return _response.data
