---
name: Install OPIK SDK and run E2E lib tests
description: Install OPIK SDK with test dependencies and executes E2E integration tests for particular library
inputs:
  library_name:
    required: true
    description: "The library name"

runs:
  using: composite
  steps:
    - name: Create virtual environment for ${{inputs.library_name}}
      shell: bash
      run: |
        uv venv ${{inputs.library_name}}-env
        source ${{inputs.library_name}}-env/bin/activate

    - name: Install OPIK, test requirements, and run tests for ${{inputs.library_name}}
      shell: bash
      run: |
        # Install OPIK
        uv pip install ${{ github.workspace }}    
        # Install test dependencies
        cd ${{ github.workspace }}/tests
        uv pip install --no-cache-dir --disable-pip-version-check -r test_requirements.txt
        uv pip install --no-cache-dir --disable-pip-version-check -r e2e_library_integration/${{inputs.library_name}}/requirements.txt
        uv pip list

    - name: Run E2E lib integration tests
      shell: bash
      run: |
        export OPIK_URL_OVERRIDE=http://localhost:5173/api
        export OPIK_CONSOLE_LOGGING_LEVEL=DEBUG
        cd ${{ github.workspace }}/tests/e2e_library_integration/${{inputs.library_name}}/
        uv run pytest  -vv .

    - name: Deactivate virtual environment for ${{inputs.library_name}}
      shell: bash
      run: deactivate