// This file was auto-generated by Fern from our API Definition.

export const SpanSearchStreamRequestPublicType = {
    General: "general",
    Tool: "tool",
    Llm: "llm",
    Guardrail: "guardrail",
} as const;
export type SpanSearchStreamRequestPublicType =
    (typeof SpanSearchStreamRequestPublicType)[keyof typeof SpanSearchStreamRequestPublicType];
