build:
	rm -rf build
	sphinx-build -b html source build/html --fail-on-warning

dev:
	rm -rf build
	sphinx-autobuild source build/html --fail-on-warning

.PHONY: generate-python-sdk-documentation python-sdk-docs-dev
