// This file was auto-generated by Fern from our API Definition.

export interface AuthorizationServerMetadata {
    issuer?: string;
    authorizationEndpoint?: string;
    tokenEndpoint?: string;
    revocationEndpoint?: string;
    registrationEndpoint?: string;
    responseTypesSupported?: string[];
    grantTypesSupported?: string[];
    codeChallengeMethodsSupported?: string[];
    tokenEndpointAuthMethodsSupported?: string[];
}
