// This file was auto-generated by Fern from our API Definition.

export interface ClientRegistrationResponse {
    clientId?: string;
    clientIdIssuedAt?: number;
    clientName?: string;
    logoUri?: string;
    softwareId?: string;
    softwareVersion?: string;
    clientUri?: string;
    redirectUris?: string[];
    tokenEndpointAuthMethod?: string;
    grantTypes?: string[];
    responseTypes?: string[];
}
