// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../index.js";

export interface DatasetItemPageCompare {
    content?: OpikApi.DatasetItemCompare[];
    page?: number;
    size?: number;
    total?: number;
    columns?: OpikApi.ColumnCompare[];
    sortableBy?: string[];
}
