// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../index.js";

export interface DatasetItemWrite {
    /**
     * Stable item identifier.
     * On write, used as the upsert key.
     * If omitted, a new ID is generated.
     * Remains the same across dataset versions
     */
    id?: string;
    traceId?: string;
    spanId?: string;
    source: OpikApi.DatasetItemWriteSource;
    data: OpikApi.JsonNode;
    description?: string;
    tags?: string[];
    evaluators?: OpikApi.EvaluatorItemWrite[];
    executionPolicy?: OpikApi.ExecutionPolicyWrite;
}
