// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../index.js";

export interface DatasetItemPublic {
    id?: string;
    datasetItemId?: string;
    traceId?: string;
    spanId?: string;
    source: OpikApi.DatasetItemPublicSource;
    data: OpikApi.JsonNode;
    description?: string;
    tags?: string[];
    evaluators?: OpikApi.EvaluatorItemPublic[];
    executionPolicy?: OpikApi.ExecutionPolicyPublic;
    experimentItems?: OpikApi.ExperimentItemPublic[];
    runSummariesByExperiment?: Record<string, OpikApi.ExperimentRunSummaryPublic>;
    datasetId?: string;
    createdAt?: Date;
    lastUpdatedAt?: Date;
    createdBy?: string;
    lastUpdatedBy?: string;
}
