// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../index.js";

export interface DatasetItemBatch {
    /** If null, dataset_id must be provided */
    datasetName?: string;
    /** If null, dataset_name must be provided */
    datasetId?: string;
    /** Optional. Associates the batch with a project by name. Ignored if project_id is provided. */
    projectName?: string;
    /** Optional. Associates the batch with a project by ID. Takes precedence over project_name. */
    projectId?: string;
    items: OpikApi.DatasetItem[];
    /** Optional batch group ID to group multiple batches into a single dataset version. If null, mutates the latest version instead of creating a new one. */
    batchGroupId?: string;
    /** OPIK-6696. Optional. Dataset to read carry-forward rows from when materializing the new version. Required together with copy_from_version_id. When both are set, the INSERT FROM SELECT that copies unchanged rows reads from this (dataset, version) pair instead of the destination dataset's prior version, avoiding the multi-replica read-after-write window. When null, the existing behavior applies (reads from the destination's prior version). */
    copyFromDatasetId?: string;
    /** OPIK-6696. Optional. Version within copy_from_dataset_id to read carry-forward rows from. Required together with copy_from_dataset_id. */
    copyFromVersionId?: string;
}
