/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DatasetVisibility = "private" | "public";
export const DatasetVisibility = {
    Private: "private",
    Public: "public",
} as const;
