/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpikApi from "../index";

export interface DatasetItemPublic {
    id?: string;
    traceId?: string;
    spanId?: string;
    source: OpikApi.DatasetItemPublicSource;
    data: OpikApi.JsonNode;
    experimentItems?: OpikApi.ExperimentItemPublic[];
    createdAt?: Date;
    lastUpdatedAt?: Date;
    createdBy?: string;
    lastUpdatedBy?: string;
}
