/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DeltaRole = "system" | "user" | "assistant" | "tool" | "function";
export const DeltaRole = {
    System: "system",
    User: "user",
    Assistant: "assistant",
    Tool: "tool",
    Function: "function",
} as const;
