/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpikApi from "../index";

export interface Descriptor {
    index?: number;
    proto?: OpikApi.DescriptorProto;
    options?: OpikApi.MessageOptions;
    fullName?: string;
    file?: OpikApi.FileDescriptor;
    containingType?: OpikApi.Descriptor;
    nestedTypes?: OpikApi.Descriptor[];
    enumTypes?: OpikApi.EnumDescriptor[];
    fields?: OpikApi.FieldDescriptor[];
    extensions?: OpikApi.FieldDescriptor[];
    oneofs?: OpikApi.OneofDescriptor[];
    name?: string;
    extendable?: boolean;
    realOneofs?: OpikApi.OneofDescriptor[];
}
