// This file was auto-generated by Fern from our API Definition.

export const ExperimentItemTraceVisibilityMode = {
    Default: "default",
    Hidden: "hidden",
} as const;
export type ExperimentItemTraceVisibilityMode =
    (typeof ExperimentItemTraceVisibilityMode)[keyof typeof ExperimentItemTraceVisibilityMode];
