/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ExperimentType = "regular" | "trial" | "mini-batch";
export const ExperimentType = {
    Regular: "regular",
    Trial: "trial",
    MiniBatch: "mini-batch",
} as const;
