/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FeedbackScoreBatchTracingItemTracingSource = "ui" | "sdk" | "online_scoring";
export const FeedbackScoreBatchTracingItemTracingSource = {
    Ui: "ui",
    Sdk: "sdk",
    OnlineScoring: "online_scoring",
} as const;
