/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpikApi from "../index";

export type Feedback = OpikApi.Feedback.Numerical | OpikApi.Feedback.Categorical;

export declare namespace Feedback {
    interface Numerical extends OpikApi.NumericalFeedbackDefinition, _Base {
        type: "numerical";
    }

    interface Categorical extends OpikApi.CategoricalFeedbackDefinition, _Base {
        type: "categorical";
    }

    interface _Base {
        id?: string;
        name: string;
        createdAt?: Date;
        createdBy?: string;
        lastUpdatedAt?: Date;
        lastUpdatedBy?: string;
    }
}
