/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GuardrailWriteResult = "passed" | "failed";
export const GuardrailWriteResult = {
    Passed: "passed",
    Failed: "failed",
} as const;
