// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../index.js";

export interface LocalRunnerJob {
    id?: string;
    runnerId?: string;
    agentName?: string;
    status?: OpikApi.LocalRunnerJobStatus;
    inputs?: OpikApi.JsonNode;
    result?: OpikApi.JsonNode;
    error?: string;
    project?: string;
    traceId?: string;
    timeout?: number;
    createdAt?: Date;
    startedAt?: Date;
    completedAt?: Date;
}
