// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../index.js";

export interface OptimizationStudioConfig {
    datasetName: string;
    prompt: OpikApi.StudioPrompt;
    llmModel: OpikApi.StudioLlmModel;
    evaluation: OpikApi.StudioEvaluation;
    optimizer: OpikApi.StudioOptimizer;
}
