// This file was auto-generated by Fern from our API Definition.

export const ProjectDetailedVisibility = {
    Private: "private",
    Public: "public",
} as const;
export type ProjectDetailedVisibility = (typeof ProjectDetailedVisibility)[keyof typeof ProjectDetailedVisibility];
