/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProjectMetricResponsePublicMetricType =
    | "FEEDBACK_SCORES"
    | "TRACE_COUNT"
    | "TOKEN_USAGE"
    | "DURATION"
    | "COST"
    | "GUARDRAILS_FAILED_COUNT";
export const ProjectMetricResponsePublicMetricType = {
    FeedbackScores: "FEEDBACK_SCORES",
    TraceCount: "TRACE_COUNT",
    TokenUsage: "TOKEN_USAGE",
    Duration: "DURATION",
    Cost: "COST",
    GuardrailsFailedCount: "GUARDRAILS_FAILED_COUNT",
} as const;
