/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpikApi from "../index";

export interface PromptVersionPagePublic {
    page?: number;
    size?: number;
    total?: number;
    content?: OpikApi.PromptVersionPublic[];
    sortableBy?: string[];
}
