/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpikApi from "../index";

export interface ResourceSpans {
    unknownFields?: OpikApi.UnknownFieldSet;
    resource?: OpikApi.Resource;
    defaultInstanceForType?: OpikApi.ResourceSpans;
    scopeSpansOrBuilderList?: OpikApi.ScopeSpansOrBuilder[];
    resourceOrBuilder?: OpikApi.ResourceOrBuilder;
    scopeSpansList?: OpikApi.ScopeSpans[];
    scopeSpansCount?: number;
    schemaUrlBytes?: OpikApi.ByteString;
    serializedSize?: number;
    parserForType?: OpikApi.ParserResourceSpans;
    schemaUrl?: string;
    initialized?: boolean;
    initializationErrorString?: string;
    descriptorForType?: OpikApi.Descriptor;
    allFields?: Record<string, Record<string, unknown>>;
    memoizedSerializedSize?: number;
}
