/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpikApi from "../index";

export interface SourceCodeInfo {
    unknownFields?: OpikApi.UnknownFieldSet;
    locationOrBuilderList?: OpikApi.LocationOrBuilder[];
    defaultInstanceForType?: OpikApi.SourceCodeInfo;
    locationList?: OpikApi.Location[];
    locationCount?: number;
    serializedSize?: number;
    parserForType?: OpikApi.ParserSourceCodeInfo;
    initialized?: boolean;
    allFieldsRaw?: Record<string, Record<string, unknown>>;
    allFields?: Record<string, Record<string, unknown>>;
    initializationErrorString?: string;
    descriptorForType?: OpikApi.Descriptor;
    memoizedSerializedSize?: number;
}
