/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SpanOrBuilderKind =
    | "SPAN_KIND_UNSPECIFIED"
    | "SPAN_KIND_INTERNAL"
    | "SPAN_KIND_SERVER"
    | "SPAN_KIND_CLIENT"
    | "SPAN_KIND_PRODUCER"
    | "SPAN_KIND_CONSUMER"
    | "UNRECOGNIZED";
export const SpanOrBuilderKind = {
    SpanKindUnspecified: "SPAN_KIND_UNSPECIFIED",
    SpanKindInternal: "SPAN_KIND_INTERNAL",
    SpanKindServer: "SPAN_KIND_SERVER",
    SpanKindClient: "SPAN_KIND_CLIENT",
    SpanKindProducer: "SPAN_KIND_PRODUCER",
    SpanKindConsumer: "SPAN_KIND_CONSUMER",
    Unrecognized: "UNRECOGNIZED",
} as const;
