/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpikApi from "../index";

export interface SpanFilter {
    field?: string;
    operator?: OpikApi.SpanFilterOperator;
    key?: string;
    value?: string;
}
