// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../index.js";

export interface StudioLlmModel {
    model: string;
    parameters?: OpikApi.JsonNode;
}
