/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpikApi from "../index";

export interface TraceThreadLlmAsJudgeCodePublic {
    model: OpikApi.LlmAsJudgeModelParametersPublic;
    messages: OpikApi.LlmAsJudgeMessagePublic[];
    schema: OpikApi.LlmAsJudgeOutputSchemaPublic[];
}
