// This file was auto-generated by Fern from our API Definition.

export const TraceFilterPublicOperator = {
    Contains: "contains",
    NotContains: "not_contains",
    StartsWith: "starts_with",
    EndsWith: "ends_with",
    EqualTo: "=",
    NotEquals: "!=",
    GreaterThan: ">",
    GreaterThanOrEqualTo: ">=",
    LessThan: "<",
    LessThanOrEqualTo: "<=",
    IsEmpty: "is_empty",
    IsNotEmpty: "is_not_empty",
} as const;
export type TraceFilterPublicOperator = (typeof TraceFilterPublicOperator)[keyof typeof TraceFilterPublicOperator];
