/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OpikApi from "../../../../index";

/**
 * @example
 *     {
 *         annotationQueues: [{
 *                 projectId: "project_id",
 *                 name: "name",
 *                 scope: "trace"
 *             }]
 *     }
 */
export interface AnnotationQueueBatchWrite {
    /** List of annotation queues to create */
    annotationQueues: OpikApi.AnnotationQueueWrite[];
}
