// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../index.js";

/**
 * @example
 *     {
 *         projectId: "project_id",
 *         activationKey: "activation_key",
 *         type: "connect"
 *     }
 */
export interface CreateSessionRequest {
    projectId: string;
    activationKey: string;
    ttlSeconds?: number;
    type: OpikApi.CreateSessionRequestType;
}
