package com.comet.opik.api.filter;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum SpanField implements Field {
    ID(ID_QUERY_PARAM, FieldType.STRING),
    NAME(NAME_QUERY_PARAM, FieldType.STRING),
    START_TIME(START_TIME_QUERY_PARAM, FieldType.DATE_TIME),
    END_TIME(END_TIME_QUERY_PARAM, FieldType.DATE_TIME),
    INPUT(INPUT_QUERY_PARAM, FieldType.STRING),
    OUTPUT(OUTPUT_QUERY_PARAM, FieldType.STRING),
    INPUT_JSON(INPUT_JSON_QUERY_PARAM, FieldType.DICTIONARY),
    OUTPUT_JSON(OUTPUT_JSON_QUERY_PARAM, FieldType.DICTIONARY),
    METADATA(METADATA_QUERY_PARAM, FieldType.DICTIONARY),
    MODEL(MODEL_QUERY_PARAM, FieldType.STRING),
    PROVIDER(PROVIDER_QUERY_PARAM, FieldType.STRING),
    TOTAL_ESTIMATED_COST(TOTAL_ESTIMATED_COST_QUERY_PARAM, FieldType.NUMBER),
    TAGS(TAGS_QUERY_PARAM, FieldType.LIST),
    USAGE_COMPLETION_TOKENS(USAGE_COMPLETION_TOKENS_QUERY_PARAM, FieldType.NUMBER),
    USAGE_PROMPT_TOKENS(USAGE_PROMPT_TOKENS_QUERY_PARAM, FieldType.NUMBER),
    USAGE_TOTAL_TOKENS(USAGE_TOTAL_TOKEN_QUERY_PARAMS, FieldType.NUMBER),
    FEEDBACK_SCORES(FEEDBACK_SCORES_QUERY_PARAM, FieldType.FEEDBACK_SCORES_NUMBER),
    DURATION(DURATION_QUERY_PARAM, FieldType.NUMBER),
    TTFT(TTFT_QUERY_PARAM, FieldType.NUMBER),
    ERROR_INFO(ERROR_INFO_QUERY_PARAM, FieldType.ERROR_CONTAINER),
    TYPE(TYPE_QUERY_PARAM, FieldType.ENUM),
    TRACE_ID(TRACE_ID_QUERY_PARAM, FieldType.STRING),
    CUSTOM(CUSTOM_QUERY_PARAM, FieldType.CUSTOM),
    ;

    private final String queryParamField;
    private final FieldType type;
}
