// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const GetSpansByProjectRequestType: core.serialization.Schema<
    serializers.GetSpansByProjectRequestType.Raw,
    OpikApi.GetSpansByProjectRequestType
> = core.serialization.enum_(["general", "tool", "llm", "guardrail"]);

export declare namespace GetSpansByProjectRequestType {
    export type Raw = "general" | "tool" | "llm" | "guardrail";
}
