name: Feature Request
description: File a feature request.
title: "[FR]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request.
        #### To help us prioritize your request, please provide fill in this feature request template.
  - type: textarea
    attributes:
      label: Proposal summary
      description: Provide a brief summary of your feature request. Adding a code (or pseudo-code) snippet that describes your use-case or the way you would like the feature to work is highly appreciated. The details help the team to process your request faster.
    validations:
      required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Motivation
      description: |
        Describe the motivation for your feature request, this can include:
        - What problem are you trying to solve?
        - How are you currently solving this problem?
        - What are the benefits of this feature?
