repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: ^tests_end_to_end
      - id: end-of-file-fixer
        files: ^tests_end_to_end

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes]
        files: ^tests_end_to_end
      - id: ruff-format
        files: ^tests_end_to_end

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^tests_end_to_end
        args: [--config-file, tests_end_to_end/pyproject.toml]
        additional_dependencies: ['types-PyYAML']
