package com.comet.opik.api.metrics;

public enum MetricType {
    FEEDBACK_SCORES,
    TRACE_COUNT,
    TOKEN_USAGE,
    DURATION,
    COST,
    GUARDRAILS_FAILED_COUNT,
    THREAD_COUNT,
    THREAD_DURATION,
    THREAD_FEEDBACK_SCORES,
    SPAN_FEEDBACK_SCORES,
    SPAN_COUNT,
    SPAN_DURATION,
    SPAN_TOKEN_USAGE,
}
