# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .assistant_message_role import AssistantMessageRole
from .function_call import FunctionCall
from .tool_call import ToolCall


class AssistantMessage(UniversalBaseModel):
    role: typing.Optional[AssistantMessageRole] = None
    content: typing.Optional[str] = None
    reasoning_content: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="reasoningContent")] = None
    name: typing.Optional[str] = None
    tool_calls: typing_extensions.Annotated[
        typing.Optional[typing.List[ToolCall]], FieldMetadata(alias="toolCalls")
    ] = None
    refusal: typing.Optional[str] = None
    function_call: typing_extensions.Annotated[typing.Optional[FunctionCall], FieldMetadata(alias="functionCall")] = (
        None
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
