# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
from ..core.pydantic_utilities import UniversalBaseModel
from .unknown_field_set import UnknownFieldSet
from .message_lite import MessageLite
import typing_extensions
import typing
from ..core.serialization import FieldMetadata
from .parser_enum_value_descriptor_proto import ParserEnumValueDescriptorProto
from .byte_string import ByteString
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic
from ..core.pydantic_utilities import update_forward_refs


class EnumValueDescriptorProto(UniversalBaseModel):
    unknown_fields: typing_extensions.Annotated[
        typing.Optional[UnknownFieldSet], FieldMetadata(alias="unknownFields")
    ] = None
    name: typing.Optional[str] = None
    number: typing.Optional[int] = None
    default_instance_for_type: typing_extensions.Annotated[
        typing.Optional["EnumValueDescriptorProto"],
        FieldMetadata(alias="defaultInstanceForType"),
    ] = None
    options_or_builder: typing_extensions.Annotated[
        typing.Optional["EnumValueOptionsOrBuilder"],
        FieldMetadata(alias="optionsOrBuilder"),
    ] = None
    serialized_size: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="serializedSize")
    ] = None
    parser_for_type: typing_extensions.Annotated[
        typing.Optional[ParserEnumValueDescriptorProto],
        FieldMetadata(alias="parserForType"),
    ] = None
    name_bytes: typing_extensions.Annotated[
        typing.Optional[ByteString], FieldMetadata(alias="nameBytes")
    ] = None
    initialized: typing.Optional[bool] = None
    options: typing.Optional["EnumValueOptions"] = None
    initialization_error_string: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="initializationErrorString")
    ] = None
    descriptor_for_type: typing_extensions.Annotated[
        typing.Optional["Descriptor"], FieldMetadata(alias="descriptorForType")
    ] = None
    all_fields: typing_extensions.Annotated[
        typing.Optional[
            typing.Dict[str, typing.Dict[str, typing.Optional[typing.Any]]]
        ],
        FieldMetadata(alias="allFields"),
    ] = None
    memoized_serialized_size: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="memoizedSerializedSize")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .declaration import Declaration  # noqa: E402
from .declaration_or_builder import DeclarationOrBuilder  # noqa: E402
from .descriptor import Descriptor  # noqa: E402
from .descriptor_proto import DescriptorProto  # noqa: E402
from .descriptor_proto_or_builder import DescriptorProtoOrBuilder  # noqa: E402
from .edition_default import EditionDefault  # noqa: E402
from .edition_default_or_builder import EditionDefaultOrBuilder  # noqa: E402
from .enum_descriptor import EnumDescriptor  # noqa: E402
from .enum_descriptor_proto import EnumDescriptorProto  # noqa: E402
from .enum_descriptor_proto_or_builder import EnumDescriptorProtoOrBuilder  # noqa: E402
from .enum_options import EnumOptions  # noqa: E402
from .enum_options_or_builder import EnumOptionsOrBuilder  # noqa: E402
from .enum_reserved_range import EnumReservedRange  # noqa: E402
from .enum_reserved_range_or_builder import EnumReservedRangeOrBuilder  # noqa: E402
from .enum_value_descriptor import EnumValueDescriptor  # noqa: E402
from .enum_value_descriptor_proto_or_builder import EnumValueDescriptorProtoOrBuilder  # noqa: E402
from .enum_value_options import EnumValueOptions  # noqa: E402
from .enum_value_options_or_builder import EnumValueOptionsOrBuilder  # noqa: E402
from .extension_range import ExtensionRange  # noqa: E402
from .extension_range_options import ExtensionRangeOptions  # noqa: E402
from .extension_range_options_or_builder import ExtensionRangeOptionsOrBuilder  # noqa: E402
from .extension_range_or_builder import ExtensionRangeOrBuilder  # noqa: E402
from .feature_set import FeatureSet  # noqa: E402
from .feature_set_or_builder import FeatureSetOrBuilder  # noqa: E402
from .feature_support import FeatureSupport  # noqa: E402
from .feature_support_or_builder import FeatureSupportOrBuilder  # noqa: E402
from .field_descriptor import FieldDescriptor  # noqa: E402
from .field_descriptor_proto import FieldDescriptorProto  # noqa: E402
from .field_descriptor_proto_or_builder import FieldDescriptorProtoOrBuilder  # noqa: E402
from .field_options import FieldOptions  # noqa: E402
from .field_options_or_builder import FieldOptionsOrBuilder  # noqa: E402
from .file_descriptor import FileDescriptor  # noqa: E402
from .file_descriptor_proto import FileDescriptorProto  # noqa: E402
from .file_options import FileOptions  # noqa: E402
from .file_options_or_builder import FileOptionsOrBuilder  # noqa: E402
from .location import Location  # noqa: E402
from .location_or_builder import LocationOrBuilder  # noqa: E402
from .message import Message  # noqa: E402
from .message_options import MessageOptions  # noqa: E402
from .message_options_or_builder import MessageOptionsOrBuilder  # noqa: E402
from .method_descriptor import MethodDescriptor  # noqa: E402
from .method_descriptor_proto import MethodDescriptorProto  # noqa: E402
from .method_descriptor_proto_or_builder import MethodDescriptorProtoOrBuilder  # noqa: E402
from .method_options import MethodOptions  # noqa: E402
from .method_options_or_builder import MethodOptionsOrBuilder  # noqa: E402
from .name_part import NamePart  # noqa: E402
from .name_part_or_builder import NamePartOrBuilder  # noqa: E402
from .oneof_descriptor import OneofDescriptor  # noqa: E402
from .oneof_descriptor_proto import OneofDescriptorProto  # noqa: E402
from .oneof_descriptor_proto_or_builder import OneofDescriptorProtoOrBuilder  # noqa: E402
from .oneof_options import OneofOptions  # noqa: E402
from .oneof_options_or_builder import OneofOptionsOrBuilder  # noqa: E402
from .reserved_range import ReservedRange  # noqa: E402
from .reserved_range_or_builder import ReservedRangeOrBuilder  # noqa: E402
from .service_descriptor import ServiceDescriptor  # noqa: E402
from .service_descriptor_proto import ServiceDescriptorProto  # noqa: E402
from .service_descriptor_proto_or_builder import ServiceDescriptorProtoOrBuilder  # noqa: E402
from .service_options import ServiceOptions  # noqa: E402
from .service_options_or_builder import ServiceOptionsOrBuilder  # noqa: E402
from .source_code_info import SourceCodeInfo  # noqa: E402
from .source_code_info_or_builder import SourceCodeInfoOrBuilder  # noqa: E402
from .uninterpreted_option import UninterpretedOption  # noqa: E402
from .uninterpreted_option_or_builder import UninterpretedOptionOrBuilder  # noqa: E402

update_forward_refs(UnknownFieldSet, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(Declaration, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    DeclarationOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(Descriptor, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(DescriptorProto, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    DescriptorProtoOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(EditionDefault, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    EditionDefaultOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(EnumDescriptor, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    EnumDescriptorProto, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    EnumDescriptorProtoOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(EnumOptions, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    EnumOptionsOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    EnumReservedRange, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    EnumReservedRangeOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    EnumValueDescriptor, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    EnumValueDescriptorProtoOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(EnumValueOptions, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    EnumValueOptionsOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(ExtensionRange, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    ExtensionRangeOptions, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    ExtensionRangeOptionsOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    ExtensionRangeOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(FeatureSet, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    FeatureSetOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(FeatureSupport, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    FeatureSupportOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(FieldDescriptor, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    FieldDescriptorProto, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    FieldDescriptorProtoOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(FieldOptions, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    FieldOptionsOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(FileDescriptor, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    FileDescriptorProto, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(FileOptions, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    FileOptionsOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(Location, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    LocationOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(Message, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(MessageLite, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(MessageOptions, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    MessageOptionsOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(MethodDescriptor, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    MethodDescriptorProto, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    MethodDescriptorProtoOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(MethodOptions, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    MethodOptionsOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(NamePart, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    NamePartOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(OneofDescriptor, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    OneofDescriptorProto, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    OneofDescriptorProtoOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(OneofOptions, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    OneofOptionsOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(ReservedRange, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    ReservedRangeOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    ServiceDescriptor, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    ServiceDescriptorProto, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    ServiceDescriptorProtoOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(ServiceOptions, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    ServiceOptionsOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(SourceCodeInfo, EnumValueDescriptorProto=EnumValueDescriptorProto)
update_forward_refs(
    SourceCodeInfoOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    UninterpretedOption, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(
    UninterpretedOptionOrBuilder, EnumValueDescriptorProto=EnumValueDescriptorProto
)
update_forward_refs(EnumValueDescriptorProto)
