# This file was auto-generated by Fern from our API Definition.

import typing

FieldOptionsOrBuilderRetention = typing.Union[
    typing.Literal["RETENTION_UNKNOWN", "RETENTION_RUNTIME", "RETENTION_SOURCE"],
    typing.Any,
]
