# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .model_tiers import ModelTiers
from .result import Result


class SpendSummaryResponse(UniversalBaseModel):
    results: typing.Optional[typing.List[Result]] = None
    spend_current: typing.Optional[typing.List[ModelTiers]] = None
    spend_previous: typing.Optional[typing.List[ModelTiers]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
