# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .item import Item


class SpendBreakdownResponse(UniversalBaseModel):
    lane_key: typing.Optional[str] = None
    title: typing.Optional[str] = None
    subtitle: typing.Optional[str] = None
    total_tokens: typing.Optional[int] = None
    item_count: typing.Optional[int] = None
    items: typing.Optional[typing.List[Item]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
