---
name: TypeScript SDK Build & Publish
description: Common steps for building and publishing TypeScript SDK packages
inputs:
  working_directory:
    required: true
    description: Working directory for the package (e.g., sdks/typescript or sdks/typescript/src/opik/integrations/opik-openai)
  version:
    required: false
    description: Version to use (if not provided, will generate from package.json + SHA)
  is_release:
    required: false
    description: Whether this is a release (publishes to NPM)
    default: "false"
  package_name:
    required: false
    description: Package name for commit message and summary (defaults to package.json name)
  npm_access:
    required: false
    description: NPM publish access (defaults to empty, use 'public' for scoped packages)
    default: ""
  enable_cache:
    required: false
    description: Enable npm cache
    default: "false"
  cache_dependency_path:
    required: false
    description: Path to package-lock.json for cache
    default: ""
  test_package_installation:
    required: false
    description: Run npm pack --dry-run test
    default: "false"
  npm_token:
    required: false
    description: NPM token for publishing
  github_token:
    required: false
    description: GitHub token for pushing changes
  skip_commit_push:
    required: false
    description: Skip commit and push (for parallel builds in release)
    default: "false"
outputs:
  version:
    description: Generated or provided version
    value: ${{ steps.set_outputs.outputs.version }}
  package_name:
    description: Package name from package.json
    value: ${{ steps.set_outputs.outputs.package_name }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        registry-url: "https://registry.npmjs.org"
        cache: ${{ inputs.enable_cache == 'true' && 'npm' || '' }}
        cache-dependency-path: ${{ inputs.cache_dependency_path }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm ci

    - name: Generate version
      id: version
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          # Use provided version
          VERSION="${{ inputs.version }}"
        else
          # For push/PR: use package.json version with short SHA (not published)
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="${PACKAGE_VERSION}-${SHORT_SHA}"
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "Generated version: ${VERSION}"

    - name: Update version
      if: ${{ inputs.is_release == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version

    - name: Build package
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm run build

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm test

    - name: Run linting
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm run lint

    - name: Run type checking
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: npm run typecheck

    - name: Test package installation (dry-run)
      if: ${{ inputs.test_package_installation == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "Testing package installation..."
        npm pack --dry-run
        echo "Package can be installed successfully"

    - name: Publish to NPM (with retry)
      id: npm_publish
      if: ${{ inputs.is_release == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        NEW_VERSION="${{ steps.version.outputs.VERSION }}"
        PACKAGE_NAME=$(node -p "require('./package.json').name")

        echo "Publishing to NPM: $PACKAGE_NAME@$NEW_VERSION"

        # Retry logic: 3 attempts with 10 second delays and 3-minute timeout per attempt
        MAX_ATTEMPTS=3
        ATTEMPT=1
        SUCCESS=false
        TIMEOUT_SECONDS=180  # 3 minutes per attempt

        PUBLISH_CMD="npm publish"
        if [ -n "${{ inputs.npm_access }}" ]; then
          PUBLISH_CMD="npm publish --access ${{ inputs.npm_access }}"
        fi

        while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
          echo "Publish attempt $ATTEMPT of $MAX_ATTEMPTS (timeout: ${TIMEOUT_SECONDS}s)..."
          
          # Use timeout command to prevent hanging indefinitely
          if timeout $TIMEOUT_SECONDS $PUBLISH_CMD; then
            SUCCESS=true
            break
          else
            EXIT_CODE=$?
            if [ $EXIT_CODE -eq 124 ]; then
              echo "Attempt $ATTEMPT timed out after ${TIMEOUT_SECONDS}s"
            else
              echo "Attempt $ATTEMPT failed with exit code $EXIT_CODE"
            fi
            
            if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
              echo "Retrying in 10 seconds..."
              sleep 10
            fi
            ATTEMPT=$((ATTEMPT + 1))
          fi
        done

        if [ "$SUCCESS" = false ]; then
          echo "Failed to publish after $MAX_ATTEMPTS attempts"
          exit 1
        fi

        # Save package name and version for summary
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
        echo "PUBLISHED_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}

    - name: Commit version changes
      if: ${{ inputs.is_release == 'true' && inputs.skip_commit_push != 'true' }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        git config --local user.email "github-actions@comet.com"
        git config --local user.name "github-actions"
        git add package.json package-lock.json
        
        PACKAGE_NAME="${{ inputs.package_name }}"
        if [ -z "$PACKAGE_NAME" ]; then
          PACKAGE_NAME=$(node -p "require('./package.json').name")
        fi
        
        git commit -m "Update $PACKAGE_NAME version to ${{ steps.version.outputs.VERSION }}"

    - name: Push changes
      if: ${{ inputs.is_release == 'true' && inputs.skip_commit_push != 'true' }}
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
        force_with_lease: true

    - name: Set outputs
      id: set_outputs
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "version=${{ steps.version.outputs.VERSION }}" >> $GITHUB_OUTPUT
        
        # Get package name from package.json
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT

