package com.comet.opik.infrastructure.llm.openrouter;

import lombok.RequiredArgsConstructor;

import java.util.Arrays;

/**
 * OpenRouter models served by the Decisions API ({@code POST /api/alpha/decisions}) instead of chat
 * completions. They answer typed questions about a text with calibrated probabilities and produce no free-form
 * text, so {@code chat/completions} rejects them.
 *
 * <p>Kept apart from {@link OpenRouterModelName} on purpose: that enum feeds the chat path (structured output,
 * LangChain4j models) and is regenerated by {@code scripts/sync_provider_models.py}, whose source list leaves
 * decisions models out.
 */
@RequiredArgsConstructor
public enum OpenRouterDecisionModel {
    TYPESAFE_JEV_LATEST("~typesafe/jev-latest"),
    TYPESAFE_JEV_1_13("typesafe/jev-1.13");

    private final String value;

    public static boolean isDecisionModel(String model) {
        return Arrays.stream(values()).anyMatch(decisionModel -> decisionModel.value.equals(model));
    }

    @Override
    public String toString() {
        return value;
    }
}
