// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const Request: core.serialization.Schema<serializers.Request.Raw, OpikApi.Request> = core.serialization.object({
    enrolled: core.serialization.boolean(),
    projectIds: core.serialization.property("project_ids", core.serialization.list(core.serialization.string())),
});

export declare namespace Request {
    export interface Raw {
        enrolled: boolean;
        project_ids: string[];
    }
}
