// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const StartMultipartUploadRequestEntityType: core.serialization.Schema<
    serializers.StartMultipartUploadRequestEntityType.Raw,
    OpikApi.StartMultipartUploadRequestEntityType
> = core.serialization.enum_(["trace", "span"]);

export declare namespace StartMultipartUploadRequestEntityType {
    export type Raw = "trace" | "span";
}
