openapi: 3.1.0
info :
  description : |
    The Opik REST API is currently in beta and subject to change. If you have any questions or feedback about the APIs, please reach out on GitHub: https://github.com/comet-ml/opik.

    All of the methods listed in this documentation are used by either the SDK or the UI to interact with the Opik server. As a result,
    the methods have been optimized for these use-cases in mind. If you are looking for a method that is not listed above, please create
    and issue on GitHub or raise a PR!

    Opik includes two main deployment options that results in slightly different API usage:

    - **Self-hosted Opik instance:** You will simply need to specify the URL as `http://localhost:5173/api/<endpoint_path>` or similar. This is the default option for the docs.
    - **Opik Cloud:** You will need to specify the Opik API Key and Opik Workspace in the header. The format of the header should be:

      ```
      {
        "Comet-Workspace": "your-workspace-name",
        "authorization": "your-api-key"
      }
      ```

      The full payload would therefore look like:
      
      ```
      curl -X GET 'https://www.comet.com/opik/api/v1/private/projects' \
      -H 'Accept: application/json' \
      -H 'Comet-Workspace: <your-workspace-name>' \
      -H 'authorization: <your-api-key>'
      ```

      Do take note here that the authorization header value does not include the `Bearer ` prefix. To switch to using the Opik Cloud in the documentation, you can
      click on the edit button displayed when hovering over the `Base URL` displayed on the right hand side of the docs.

  version : "1.0.0"
  title : "Opik REST API"
  contact :
    name : "Github Repository"
    url : "https://github.com/comet-ml/opik"
  license :
    name : "Apache 2.0"
    url : "http://www.apache.org/licenses/LICENSE-2.0.html"

servers :
  - url: http://localhost:5173/api
    description: Local server
  - url: https://www.comet.com/opik/api
    description: Opik Cloud
