// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { FeedbackScoreBatchItemThread } from "../../../../types/FeedbackScoreBatchItemThread.js";

export const FeedbackScoreBatchThread: core.serialization.Schema<
    serializers.FeedbackScoreBatchThread.Raw,
    OpikApi.FeedbackScoreBatchThread
> = core.serialization.object({
    scores: core.serialization.list(FeedbackScoreBatchItemThread),
});

export declare namespace FeedbackScoreBatchThread {
    export interface Raw {
        scores: FeedbackScoreBatchItemThread.Raw[];
    }
}
