// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AlertTriggerWrite } from "./AlertTriggerWrite.js";
import { AlertWriteAlertType } from "./AlertWriteAlertType.js";
import { WebhookWrite } from "./WebhookWrite.js";

export const AlertWrite: core.serialization.ObjectSchema<serializers.AlertWrite.Raw, OpikApi.AlertWrite> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        enabled: core.serialization.boolean().optional(),
        alertType: core.serialization.property("alert_type", AlertWriteAlertType.optional()),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
        webhook: WebhookWrite,
        triggers: core.serialization.list(AlertTriggerWrite).optional(),
    });

export declare namespace AlertWrite {
    export interface Raw {
        id?: string | null;
        name?: string | null;
        enabled?: boolean | null;
        alert_type?: AlertWriteAlertType.Raw | null;
        metadata?: Record<string, string> | null;
        webhook: WebhookWrite.Raw;
        triggers?: AlertTriggerWrite.Raw[] | null;
    }
}
