/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";

export const AnnotationQueuePublicScope: core.serialization.Schema<
    serializers.AnnotationQueuePublicScope.Raw,
    OpikApi.AnnotationQueuePublicScope
> = core.serialization.enum_(["trace", "thread"]);

export declare namespace AnnotationQueuePublicScope {
    export type Raw = "trace" | "thread";
}
