// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AuthorizationServerMetadata: core.serialization.ObjectSchema<
    serializers.AuthorizationServerMetadata.Raw,
    OpikApi.AuthorizationServerMetadata
> = core.serialization.object({
    issuer: core.serialization.string().optional(),
    authorizationEndpoint: core.serialization.property(
        "authorization_endpoint",
        core.serialization.string().optional(),
    ),
    tokenEndpoint: core.serialization.property("token_endpoint", core.serialization.string().optional()),
    revocationEndpoint: core.serialization.property("revocation_endpoint", core.serialization.string().optional()),
    registrationEndpoint: core.serialization.property("registration_endpoint", core.serialization.string().optional()),
    responseTypesSupported: core.serialization.property(
        "response_types_supported",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    grantTypesSupported: core.serialization.property(
        "grant_types_supported",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    codeChallengeMethodsSupported: core.serialization.property(
        "code_challenge_methods_supported",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    tokenEndpointAuthMethodsSupported: core.serialization.property(
        "token_endpoint_auth_methods_supported",
        core.serialization.list(core.serialization.string()).optional(),
    ),
});

export declare namespace AuthorizationServerMetadata {
    export interface Raw {
        issuer?: string | null;
        authorization_endpoint?: string | null;
        token_endpoint?: string | null;
        revocation_endpoint?: string | null;
        registration_endpoint?: string | null;
        response_types_supported?: string[] | null;
        grant_types_supported?: string[] | null;
        code_challenge_methods_supported?: string[] | null;
        token_endpoint_auth_methods_supported?: string[] | null;
    }
}
