/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";
import { TraceThreadLlmAsJudgeCodePublic } from "./TraceThreadLlmAsJudgeCodePublic";

export const AutomationRuleEvaluatorTraceThreadLlmAsJudgePublic: core.serialization.ObjectSchema<
    serializers.AutomationRuleEvaluatorTraceThreadLlmAsJudgePublic.Raw,
    OpikApi.AutomationRuleEvaluatorTraceThreadLlmAsJudgePublic
> = core.serialization.object({
    code: TraceThreadLlmAsJudgeCodePublic.optional(),
});

export declare namespace AutomationRuleEvaluatorTraceThreadLlmAsJudgePublic {
    export interface Raw {
        code?: TraceThreadLlmAsJudgeCodePublic.Raw | null;
    }
}
