// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TraceThreadFilter } from "./TraceThreadFilter.js";
import { TraceThreadUserDefinedMetricPythonCode } from "./TraceThreadUserDefinedMetricPythonCode.js";

export const AutomationRuleEvaluatorUpdateTraceThreadUserDefinedMetricPython: core.serialization.ObjectSchema<
    serializers.AutomationRuleEvaluatorUpdateTraceThreadUserDefinedMetricPython.Raw,
    OpikApi.AutomationRuleEvaluatorUpdateTraceThreadUserDefinedMetricPython
> = core.serialization.object({
    filters: core.serialization.list(TraceThreadFilter).optional(),
    code: TraceThreadUserDefinedMetricPythonCode.optional(),
});

export declare namespace AutomationRuleEvaluatorUpdateTraceThreadUserDefinedMetricPython {
    export interface Raw {
        filters?: TraceThreadFilter.Raw[] | null;
        code?: TraceThreadUserDefinedMetricPythonCode.Raw | null;
    }
}
