// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ColumnPublicTypesItem } from "./ColumnPublicTypesItem.js";

export const ColumnPublic: core.serialization.ObjectSchema<serializers.ColumnPublic.Raw, OpikApi.ColumnPublic> =
    core.serialization.object({
        name: core.serialization.string().optional(),
        types: core.serialization.list(ColumnPublicTypesItem).optional(),
        filterFieldPrefix: core.serialization.property("filter_field_prefix", core.serialization.string().optional()),
        filterField: core.serialization.string().optional(),
    });

export declare namespace ColumnPublic {
    export interface Raw {
        name?: string | null;
        types?: ColumnPublicTypesItem.Raw[] | null;
        filter_field_prefix?: string | null;
        filterField?: string | null;
    }
}
