/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";

export const DatasetItemCompareSource: core.serialization.Schema<
    serializers.DatasetItemCompareSource.Raw,
    OpikApi.DatasetItemCompareSource
> = core.serialization.enum_(["manual", "trace", "span", "sdk"]);

export declare namespace DatasetItemCompareSource {
    export type Raw = "manual" | "trace" | "span" | "sdk";
}
