/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";

export const DatasetExpansion: core.serialization.ObjectSchema<
    serializers.DatasetExpansion.Raw,
    OpikApi.DatasetExpansion
> = core.serialization.object({
    model: core.serialization.string(),
    sampleCount: core.serialization.property("sample_count", core.serialization.number().optional()),
    preserveFields: core.serialization.property(
        "preserve_fields",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    variationInstructions: core.serialization.property(
        "variation_instructions",
        core.serialization.string().optional(),
    ),
    customPrompt: core.serialization.property("custom_prompt", core.serialization.string().optional()),
});

export declare namespace DatasetExpansion {
    export interface Raw {
        model: string;
        sample_count?: number | null;
        preserve_fields?: string[] | null;
        variation_instructions?: string | null;
        custom_prompt?: string | null;
    }
}
