/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";
import { JsonNodeWrite } from "./JsonNodeWrite";
import { DatasetItemWriteSource } from "./DatasetItemWriteSource";
import { JsonNode } from "./JsonNode";
export declare const DatasetItemWrite: core.serialization.ObjectSchema<serializers.DatasetItemWrite.Raw, OpikApi.DatasetItemWrite>;
export declare namespace DatasetItemWrite {
    interface Raw {
        id?: string | null;
        input?: JsonNodeWrite.Raw | null;
        expected_output?: JsonNodeWrite.Raw | null;
        metadata?: JsonNodeWrite.Raw | null;
        trace_id?: string | null;
        span_id?: string | null;
        source: DatasetItemWriteSource.Raw;
        data?: JsonNode.Raw | null;
    }
}
