/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";
import { DatasetItemPublic } from "./DatasetItemPublic";
import { ColumnPublic } from "./ColumnPublic";

export const DatasetItemPagePublic: core.serialization.ObjectSchema<
    serializers.DatasetItemPagePublic.Raw,
    OpikApi.DatasetItemPagePublic
> = core.serialization.object({
    content: core.serialization.list(DatasetItemPublic).optional(),
    page: core.serialization.number().optional(),
    size: core.serialization.number().optional(),
    total: core.serialization.number().optional(),
    columns: core.serialization.list(ColumnPublic).optional(),
    sortableBy: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace DatasetItemPagePublic {
    export interface Raw {
        content?: DatasetItemPublic.Raw[] | null;
        page?: number | null;
        size?: number | null;
        total?: number | null;
        columns?: ColumnPublic.Raw[] | null;
        sortableBy?: string[] | null;
    }
}
