/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";

export const DataPointNumberPublic: core.serialization.ObjectSchema<
    serializers.DataPointNumberPublic.Raw,
    OpikApi.DataPointNumberPublic
> = core.serialization.object({
    time: core.serialization.date(),
    value: core.serialization.number().optional(),
});

export declare namespace DataPointNumberPublic {
    export interface Raw {
        time: string;
        value?: number | null;
    }
}
