// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DatasetVersionDiffStats } from "./DatasetVersionDiffStats.js";

export const DatasetVersionDiff: core.serialization.ObjectSchema<
    serializers.DatasetVersionDiff.Raw,
    OpikApi.DatasetVersionDiff
> = core.serialization.object({
    fromVersion: core.serialization.property("from_version", core.serialization.string().optional()),
    toVersion: core.serialization.property("to_version", core.serialization.string().optional()),
    statistics: DatasetVersionDiffStats.optional(),
});

export declare namespace DatasetVersionDiff {
    export interface Raw {
        from_version?: string | null;
        to_version?: string | null;
        statistics?: DatasetVersionDiffStats.Raw | null;
    }
}
