/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";

export const FeatureSetFieldPresence: core.serialization.Schema<
    serializers.FeatureSetFieldPresence.Raw,
    OpikApi.FeatureSetFieldPresence
> = core.serialization.enum_(["FIELD_PRESENCE_UNKNOWN", "EXPLICIT", "IMPLICIT", "LEGACY_REQUIRED"]);

export declare namespace FeatureSetFieldPresence {
    export type Raw = "FIELD_PRESENCE_UNKNOWN" | "EXPLICIT" | "IMPLICIT" | "LEGACY_REQUIRED";
}
