/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../core";
import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import { NumericalFeedbackDefinitionPublic } from "./NumericalFeedbackDefinitionPublic";
import { CategoricalFeedbackDefinitionPublic } from "./CategoricalFeedbackDefinitionPublic";

const _Base = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    createdAt: core.serialization.date().optional(),
    createdBy: core.serialization.string().optional(),
    lastUpdatedAt: core.serialization.date().optional(),
    lastUpdatedBy: core.serialization.string().optional(),
});
export const FeedbackObjectPublic: core.serialization.Schema<
    serializers.FeedbackObjectPublic.Raw,
    OpikApi.FeedbackObjectPublic
> = core.serialization
    .union("type", {
        numerical: NumericalFeedbackDefinitionPublic.extend(_Base),
        categorical: CategoricalFeedbackDefinitionPublic.extend(_Base),
    })
    .transform<OpikApi.FeedbackObjectPublic>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace FeedbackObjectPublic {
    export type Raw = FeedbackObjectPublic.Numerical | FeedbackObjectPublic.Categorical;

    export interface Numerical extends _Base, NumericalFeedbackDefinitionPublic.Raw {
        type: "numerical";
    }

    export interface Categorical extends _Base, CategoricalFeedbackDefinitionPublic.Raw {
        type: "categorical";
    }

    export interface _Base {
        id?: string | null;
        name: string;
        description?: string | null;
        createdAt?: string | null;
        createdBy?: string | null;
        lastUpdatedAt?: string | null;
        lastUpdatedBy?: string | null;
    }
}
