// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { FeedbackObjectPublic } from "./FeedbackObjectPublic.js";

export const FeedbackDefinitionPagePublic: core.serialization.ObjectSchema<
    serializers.FeedbackDefinitionPagePublic.Raw,
    OpikApi.FeedbackDefinitionPagePublic
> = core.serialization.object({
    page: core.serialization.number().optional(),
    size: core.serialization.number().optional(),
    total: core.serialization.number().optional(),
    content: core.serialization.list(FeedbackObjectPublic).optional(),
});

export declare namespace FeedbackDefinitionPagePublic {
    export interface Raw {
        page?: number | null;
        size?: number | null;
        total?: number | null;
        content?: FeedbackObjectPublic.Raw[] | null;
    }
}
