/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../core";
import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import { NumericalFeedbackDefinition } from "./NumericalFeedbackDefinition";
import { CategoricalFeedbackDefinition } from "./CategoricalFeedbackDefinition";
import { BooleanFeedbackDefinition } from "./BooleanFeedbackDefinition";

const _Base = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    createdAt: core.serialization.date().optional(),
    createdBy: core.serialization.string().optional(),
    lastUpdatedAt: core.serialization.date().optional(),
    lastUpdatedBy: core.serialization.string().optional(),
});
export const Feedback: core.serialization.Schema<serializers.Feedback.Raw, OpikApi.Feedback> = core.serialization
    .union("type", {
        numerical: NumericalFeedbackDefinition.extend(_Base),
        categorical: CategoricalFeedbackDefinition.extend(_Base),
        boolean: BooleanFeedbackDefinition.extend(_Base),
    })
    .transform<OpikApi.Feedback>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace Feedback {
    export type Raw = Feedback.Numerical | Feedback.Categorical | Feedback.Boolean;

    export interface Numerical extends _Base, NumericalFeedbackDefinition.Raw {
        type: "numerical";
    }

    export interface Categorical extends _Base, CategoricalFeedbackDefinition.Raw {
        type: "categorical";
    }

    export interface Boolean extends _Base, BooleanFeedbackDefinition.Raw {
        type: "boolean";
    }

    export interface _Base {
        id?: string | null;
        name: string;
        description?: string | null;
        createdAt?: string | null;
        createdBy?: string | null;
        lastUpdatedAt?: string | null;
        lastUpdatedBy?: string | null;
    }
}
