/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";

export const FunctionCall: core.serialization.ObjectSchema<serializers.FunctionCall.Raw, OpikApi.FunctionCall> =
    core.serialization.object({
        name: core.serialization.string().optional(),
        arguments: core.serialization.string().optional(),
    });

export declare namespace FunctionCall {
    export interface Raw {
        name?: string | null;
        arguments?: string | null;
    }
}
