// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GuardrailName: core.serialization.Schema<serializers.GuardrailName.Raw, OpikApi.GuardrailName> =
    core.serialization.enum_(["TOPIC", "PII"]);

export declare namespace GuardrailName {
    export type Raw = "TOPIC" | "PII";
}
