// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const JsonNodeDetail: core.serialization.Schema<serializers.JsonNodeDetail.Raw, OpikApi.JsonNodeDetail> =
    core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace JsonNodeDetail {
    export type Raw = Record<string, unknown>;
}
