// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LlmAsJudgeOutputSchemaWriteType } from "./LlmAsJudgeOutputSchemaWriteType.js";

export const LlmAsJudgeOutputSchemaWrite: core.serialization.ObjectSchema<
    serializers.LlmAsJudgeOutputSchemaWrite.Raw,
    OpikApi.LlmAsJudgeOutputSchemaWrite
> = core.serialization.object({
    name: core.serialization.string(),
    type: LlmAsJudgeOutputSchemaWriteType,
    description: core.serialization.string(),
});

export declare namespace LlmAsJudgeOutputSchemaWrite {
    export interface Raw {
        name: string;
        type: LlmAsJudgeOutputSchemaWriteType.Raw;
        description: string;
    }
}
