/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";
import { LlmAsJudgeOutputSchemaWriteType } from "./LlmAsJudgeOutputSchemaWriteType";

export const LlmAsJudgeOutputSchemaWrite: core.serialization.ObjectSchema<
    serializers.LlmAsJudgeOutputSchemaWrite.Raw,
    OpikApi.LlmAsJudgeOutputSchemaWrite
> = core.serialization.object({
    name: core.serialization.string(),
    type: LlmAsJudgeOutputSchemaWriteType,
    description: core.serialization.string(),
});

export declare namespace LlmAsJudgeOutputSchemaWrite {
    export interface Raw {
        name: string;
        type: LlmAsJudgeOutputSchemaWriteType.Raw;
        description: string;
    }
}
