/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";
import { ByteString } from "./ByteString";
import { ParserLocation } from "./ParserLocation";

export const Location: core.serialization.ObjectSchema<serializers.Location.Raw, OpikApi.Location> =
    core.serialization.object({
        unknownFields: core.serialization.lazyObject(() => serializers.UnknownFieldSet).optional(),
        leadingDetachedCommentsList: core.serialization.list(core.serialization.string()).optional(),
        leadingCommentsBytes: ByteString.optional(),
        trailingCommentsBytes: ByteString.optional(),
        defaultInstanceForType: core.serialization.lazyObject(() => serializers.Location).optional(),
        leadingDetachedCommentsCount: core.serialization.number().optional(),
        leadingComments: core.serialization.string().optional(),
        trailingComments: core.serialization.string().optional(),
        serializedSize: core.serialization.number().optional(),
        parserForType: ParserLocation.optional(),
        initialized: core.serialization.boolean().optional(),
        spanList: core.serialization.list(core.serialization.number()).optional(),
        pathList: core.serialization.list(core.serialization.number()).optional(),
        pathCount: core.serialization.number().optional(),
        spanCount: core.serialization.number().optional(),
        initializationErrorString: core.serialization.string().optional(),
        descriptorForType: core.serialization.lazyObject(() => serializers.Descriptor).optional(),
        allFields: core.serialization
            .record(
                core.serialization.string(),
                core.serialization.record(core.serialization.string(), core.serialization.unknown()),
            )
            .optional(),
        memoizedSerializedSize: core.serialization.number().optional(),
    });

export declare namespace Location {
    export interface Raw {
        unknownFields?: serializers.UnknownFieldSet.Raw | null;
        leadingDetachedCommentsList?: string[] | null;
        leadingCommentsBytes?: ByteString.Raw | null;
        trailingCommentsBytes?: ByteString.Raw | null;
        defaultInstanceForType?: serializers.Location.Raw | null;
        leadingDetachedCommentsCount?: number | null;
        leadingComments?: string | null;
        trailingComments?: string | null;
        serializedSize?: number | null;
        parserForType?: ParserLocation.Raw | null;
        initialized?: boolean | null;
        spanList?: number[] | null;
        pathList?: number[] | null;
        pathCount?: number | null;
        spanCount?: number | null;
        initializationErrorString?: string | null;
        descriptorForType?: serializers.Descriptor.Raw | null;
        allFields?: Record<string, Record<string, unknown>> | null;
        memoizedSerializedSize?: number | null;
    }
}
