/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";
export declare const NumericalFeedbackDetail: core.serialization.ObjectSchema<serializers.NumericalFeedbackDetail.Raw, OpikApi.NumericalFeedbackDetail>;
export declare namespace NumericalFeedbackDetail {
    interface Raw {
        max: number;
        min: number;
    }
}
