/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";
export declare const NumericalFeedbackDetailPublic: core.serialization.ObjectSchema<serializers.NumericalFeedbackDetailPublic.Raw, OpikApi.NumericalFeedbackDetailPublic>;
export declare namespace NumericalFeedbackDetailPublic {
    interface Raw {
        max: number;
        min: number;
    }
}
