/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";

export const ParserLink: core.serialization.Schema<serializers.ParserLink.Raw, OpikApi.ParserLink> =
    core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ParserLink {
    export type Raw = Record<string, unknown>;
}
