// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ErrorCountWithDeviation } from "./ErrorCountWithDeviation.js";
import { FeedbackScoreAverage } from "./FeedbackScoreAverage.js";
import { PercentageValues } from "./PercentageValues.js";

export const ProjectStatsSummaryItem: core.serialization.ObjectSchema<
    serializers.ProjectStatsSummaryItem.Raw,
    OpikApi.ProjectStatsSummaryItem
> = core.serialization.object({
    projectId: core.serialization.property("project_id", core.serialization.string().optional()),
    feedbackScores: core.serialization.property(
        "feedback_scores",
        core.serialization.list(FeedbackScoreAverage).optional(),
    ),
    duration: PercentageValues.optional(),
    totalEstimatedCost: core.serialization.property("total_estimated_cost", core.serialization.number().optional()),
    totalEstimatedCostSum: core.serialization.property(
        "total_estimated_cost_sum",
        core.serialization.number().optional(),
    ),
    usage: core.serialization.record(core.serialization.string(), core.serialization.number()).optional(),
    traceCount: core.serialization.property("trace_count", core.serialization.number().optional()),
    threadCount: core.serialization.property("thread_count", core.serialization.number().optional()),
    guardrailsFailedCount: core.serialization.property(
        "guardrails_failed_count",
        core.serialization.number().optional(),
    ),
    errorCount: core.serialization.property("error_count", ErrorCountWithDeviation.optional()),
});

export declare namespace ProjectStatsSummaryItem {
    export interface Raw {
        project_id?: string | null;
        feedback_scores?: FeedbackScoreAverage.Raw[] | null;
        duration?: PercentageValues.Raw | null;
        total_estimated_cost?: number | null;
        total_estimated_cost_sum?: number | null;
        usage?: Record<string, number> | null;
        trace_count?: number | null;
        thread_count?: number | null;
        guardrails_failed_count?: number | null;
        error_count?: ErrorCountWithDeviation.Raw | null;
    }
}
