// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ProviderAuthConfigPublicSendAs: core.serialization.Schema<
    serializers.ProviderAuthConfigPublicSendAs.Raw,
    OpikApi.ProviderAuthConfigPublicSendAs
> = core.serialization.enum_(["form", "json", "basic"]);

export declare namespace ProviderAuthConfigPublicSendAs {
    export type Raw = "form" | "json" | "basic";
}
