// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SpanFilterPublicOperator } from "./SpanFilterPublicOperator.js";

export const SpanFilterPublic: core.serialization.ObjectSchema<
    serializers.SpanFilterPublic.Raw,
    OpikApi.SpanFilterPublic
> = core.serialization.object({
    field: core.serialization.string().optional(),
    operator: SpanFilterPublicOperator.optional(),
    key: core.serialization.string().optional(),
    value: core.serialization.string().optional(),
});

export declare namespace SpanFilterPublic {
    export interface Raw {
        field?: string | null;
        operator?: SpanFilterPublicOperator.Raw | null;
        key?: string | null;
        value?: string | null;
    }
}
