/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OpikApi from "../../api/index";
import * as core from "../../core";

export const TracePublicVisibilityMode: core.serialization.Schema<
    serializers.TracePublicVisibilityMode.Raw,
    OpikApi.TracePublicVisibilityMode
> = core.serialization.enum_(["default", "hidden"]);

export declare namespace TracePublicVisibilityMode {
    export type Raw = "default" | "hidden";
}
