// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ValueEntryPublicSource: core.serialization.Schema<
    serializers.ValueEntryPublicSource.Raw,
    OpikApi.ValueEntryPublicSource
> = core.serialization.enum_(["ui", "sdk", "online_scoring"]);

export declare namespace ValueEntryPublicSource {
    export type Raw = "ui" | "sdk" | "online_scoring";
}
