// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const WorkspaceProjectName: core.serialization.ObjectSchema<
    serializers.WorkspaceProjectName.Raw,
    OpikApi.WorkspaceProjectName
> = core.serialization.object({
    workspaceId: core.serialization.property("workspace_id", core.serialization.string().optional()),
    projectId: core.serialization.property("project_id", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
});

export declare namespace WorkspaceProjectName {
    export interface Raw {
        workspace_id?: string | null;
        project_id?: string | null;
        name?: string | null;
    }
}
