package com.comet.opik.infrastructure.llm.antropic;

import com.comet.opik.infrastructure.llm.StructuredOutputSupported;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.Set;

/**
 * This information is taken from <a href="https://docs.anthropic.com/en/docs/about-claude/models">Anthropic docs</a>
 */
@Getter
@RequiredArgsConstructor
public enum AnthropicModelName implements StructuredOutputSupported {
    CLAUDE_SONNET_3_7("claude-3-7-sonnet-20250219"),
    CLAUDE_FABLE_5("claude-fable-5"),
    CLAUDE_HAIKU_4_5("claude-haiku-4-5-20251001"),
    CLAUDE_OPUS_4_1("claude-opus-4-1-20250805"),
    CLAUDE_OPUS_4("claude-opus-4-20250514"),
    CLAUDE_OPUS_4_5("claude-opus-4-5-20251101"),
    CLAUDE_OPUS_4_6("claude-opus-4-6"),
    CLAUDE_SONNET_4("claude-sonnet-4-20250514"),
    CLAUDE_SONNET_4_5("claude-sonnet-4-5"),
    CLAUDE_SONNET_4_5_20250929("claude-sonnet-4-5-20250929"),
    CLAUDE_SONNET_4_6("claude-sonnet-4-6"),
    CLAUDE_OPUS_4_7("claude-opus-4-7"),
    CLAUDE_OPUS_4_8("claude-opus-4-8"),
    CLAUDE_SONNET_5("claude-sonnet-5");

    private final String value;

    /**
     * API ids of Anthropic adaptive-thinking models, which reject sampling params
     * (temperature/top_p/top_k) with a {@code 400 "temperature is deprecated for this model"}.
     *
     * <p><strong>Why this is a standalone set and not a per-constant flag.</strong> The enum
     * constant list above is regenerated by the recurring "sync provider model definitions" chore
     * (e.g. #7088, #7315, #7582). That generator emits every model as a single-arg
     * {@code NAME("value")} constant and has no notion of an extra capability argument, so a
     * per-constant flag (the original #7531 shape, {@code NAME("value", false)}) is silently
     * dropped on the next sync — which is exactly how #7582 reverted the adaptive-thinking opt-out
     * and reopened issue #7526. Keeping the capability here, outside the generated constant list,
     * lets syncs add/remove/reorder constants freely without clobbering it. Referencing the enum
     * constants (rather than duplicating the string literals) means a sync that renames or removes
     * a referenced constant breaks compilation instead of drifting silently.
     *
     * <p><strong>Residual manual step.</strong> This guards against rename/removal of the
     * <em>known</em> adaptive models below; it cannot force a <em>newly synced</em> adaptive model
     * into the set. When Anthropic ships a new adaptive-thinking model, its API id must be added
     * here by hand (the durable fix is teaching the generator to emit the capability directly).
     */
    private static final Set<String> ADAPTIVE_THINKING_MODEL_IDS = Set.of(
            CLAUDE_OPUS_4_7.value,
            CLAUDE_OPUS_4_8.value,
            CLAUDE_SONNET_5.value);

    /**
     * Whether the model accepts sampling params (temperature/top_p/top_k). Adaptive-thinking models
     * reject them with a 400 and are opted out explicitly. Unknown model names default to {@code true}
     * so registry-only Anthropic models (not enumerated here) keep temperature support.
     */
    public static boolean supportsSamplingParams(String modelName) {
        return !ADAPTIVE_THINKING_MODEL_IDS.contains(modelName);
    }

    @Override
    public String toString() {
        return value;
    }

    @Override
    public boolean isStructuredOutputSupported() {
        return false;
    }
}
