// This file was auto-generated by Fern from our API Definition.

import type * as OpikApi from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreatePromptVersionDetailAction: core.serialization.Schema<
    serializers.CreatePromptVersionDetailAction.Raw,
    OpikApi.CreatePromptVersionDetailAction
> = core.serialization.enum_(["update_blueprint", "no_action"]);

export declare namespace CreatePromptVersionDetailAction {
    export type Raw = "update_blueprint" | "no_action";
}
