// This file was auto-generated by Fern from our API Definition.

import { AlertsClient } from "./api/resources/alerts/client/Client.js";
import { AnnotationQueuesClient } from "./api/resources/annotationQueues/client/Client.js";
import { AttachmentsClient } from "./api/resources/attachments/client/Client.js";
import { AutomationRuleEvaluatorsClient } from "./api/resources/automationRuleEvaluators/client/Client.js";
import { ChatCompletionsClient } from "./api/resources/chatCompletions/client/Client.js";
import { CheckClient } from "./api/resources/check/client/Client.js";
import { DashboardsClient } from "./api/resources/dashboards/client/Client.js";
import { DatasetsClient } from "./api/resources/datasets/client/Client.js";
import { ExperimentsClient } from "./api/resources/experiments/client/Client.js";
import { FeedbackDefinitionsClient } from "./api/resources/feedbackDefinitions/client/Client.js";
import { GuardrailsClient } from "./api/resources/guardrails/client/Client.js";
import { LlmProviderKeyClient } from "./api/resources/llmProviderKey/client/Client.js";
import { ManualEvaluationClient } from "./api/resources/manualEvaluation/client/Client.js";
import { OpenTelemetryIngestionClient } from "./api/resources/openTelemetryIngestion/client/Client.js";
import { OptimizationsClient } from "./api/resources/optimizations/client/Client.js";
import { ProjectsClient } from "./api/resources/projects/client/Client.js";
import { PromptsClient } from "./api/resources/prompts/client/Client.js";
import { RedirectClient } from "./api/resources/redirect/client/Client.js";
import { ServiceTogglesClient } from "./api/resources/serviceToggles/client/Client.js";
import { SpansClient } from "./api/resources/spans/client/Client.js";
import { SystemUsageClient } from "./api/resources/systemUsage/client/Client.js";
import { TracesClient } from "./api/resources/traces/client/Client.js";
import { WelcomeWizardClient } from "./api/resources/welcomeWizard/client/Client.js";
import { WorkspacesClient } from "./api/resources/workspaces/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import * as environments from "./environments.js";
import { handleNonStatusCodeError } from "./errors/handleNonStatusCodeError.js";
import * as errors from "./errors/index.js";

export declare namespace OpikApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class OpikApiClient {
    protected readonly _options: NormalizedClientOptions<OpikApiClient.Options>;
    protected _systemUsage: SystemUsageClient | undefined;
    protected _alerts: AlertsClient | undefined;
    protected _annotationQueues: AnnotationQueuesClient | undefined;
    protected _attachments: AttachmentsClient | undefined;
    protected _check: CheckClient | undefined;
    protected _automationRuleEvaluators: AutomationRuleEvaluatorsClient | undefined;
    protected _chatCompletions: ChatCompletionsClient | undefined;
    protected _dashboards: DashboardsClient | undefined;
    protected _datasets: DatasetsClient | undefined;
    protected _experiments: ExperimentsClient | undefined;
    protected _feedbackDefinitions: FeedbackDefinitionsClient | undefined;
    protected _guardrails: GuardrailsClient | undefined;
    protected _llmProviderKey: LlmProviderKeyClient | undefined;
    protected _manualEvaluation: ManualEvaluationClient | undefined;
    protected _openTelemetryIngestion: OpenTelemetryIngestionClient | undefined;
    protected _optimizations: OptimizationsClient | undefined;
    protected _projects: ProjectsClient | undefined;
    protected _prompts: PromptsClient | undefined;
    protected _serviceToggles: ServiceTogglesClient | undefined;
    protected _spans: SpansClient | undefined;
    protected _traces: TracesClient | undefined;
    protected _welcomeWizard: WelcomeWizardClient | undefined;
    protected _workspaces: WorkspacesClient | undefined;
    protected _redirect: RedirectClient | undefined;

    constructor(options: OpikApiClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get systemUsage(): SystemUsageClient {
        return (this._systemUsage ??= new SystemUsageClient(this._options));
    }

    public get alerts(): AlertsClient {
        return (this._alerts ??= new AlertsClient(this._options));
    }

    public get annotationQueues(): AnnotationQueuesClient {
        return (this._annotationQueues ??= new AnnotationQueuesClient(this._options));
    }

    public get attachments(): AttachmentsClient {
        return (this._attachments ??= new AttachmentsClient(this._options));
    }

    public get check(): CheckClient {
        return (this._check ??= new CheckClient(this._options));
    }

    public get automationRuleEvaluators(): AutomationRuleEvaluatorsClient {
        return (this._automationRuleEvaluators ??= new AutomationRuleEvaluatorsClient(this._options));
    }

    public get chatCompletions(): ChatCompletionsClient {
        return (this._chatCompletions ??= new ChatCompletionsClient(this._options));
    }

    public get dashboards(): DashboardsClient {
        return (this._dashboards ??= new DashboardsClient(this._options));
    }

    public get datasets(): DatasetsClient {
        return (this._datasets ??= new DatasetsClient(this._options));
    }

    public get experiments(): ExperimentsClient {
        return (this._experiments ??= new ExperimentsClient(this._options));
    }

    public get feedbackDefinitions(): FeedbackDefinitionsClient {
        return (this._feedbackDefinitions ??= new FeedbackDefinitionsClient(this._options));
    }

    public get guardrails(): GuardrailsClient {
        return (this._guardrails ??= new GuardrailsClient(this._options));
    }

    public get llmProviderKey(): LlmProviderKeyClient {
        return (this._llmProviderKey ??= new LlmProviderKeyClient(this._options));
    }

    public get manualEvaluation(): ManualEvaluationClient {
        return (this._manualEvaluation ??= new ManualEvaluationClient(this._options));
    }

    public get openTelemetryIngestion(): OpenTelemetryIngestionClient {
        return (this._openTelemetryIngestion ??= new OpenTelemetryIngestionClient(this._options));
    }

    public get optimizations(): OptimizationsClient {
        return (this._optimizations ??= new OptimizationsClient(this._options));
    }

    public get projects(): ProjectsClient {
        return (this._projects ??= new ProjectsClient(this._options));
    }

    public get prompts(): PromptsClient {
        return (this._prompts ??= new PromptsClient(this._options));
    }

    public get serviceToggles(): ServiceTogglesClient {
        return (this._serviceToggles ??= new ServiceTogglesClient(this._options));
    }

    public get spans(): SpansClient {
        return (this._spans ??= new SpansClient(this._options));
    }

    public get traces(): TracesClient {
        return (this._traces ??= new TracesClient(this._options));
    }

    public get welcomeWizard(): WelcomeWizardClient {
        return (this._welcomeWizard ??= new WelcomeWizardClient(this._options));
    }

    public get workspaces(): WorkspacesClient {
        return (this._workspaces ??= new WorkspacesClient(this._options));
    }

    public get redirect(): RedirectClient {
        return (this._redirect ??= new RedirectClient(this._options));
    }

    /**
     * @param {OpikApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.isAlive()
     */
    public isAlive(requestOptions?: OpikApiClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__isAlive(requestOptions));
    }

    private async __isAlive(requestOptions?: OpikApiClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Comet-Workspace": requestOptions?.workspaceName ?? this._options?.workspaceName,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OpikApiEnvironment.Default,
                "is-alive/ping",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OpikApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/is-alive/ping");
    }

    /**
     * @param {OpikApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.version()
     */
    public version(requestOptions?: OpikApiClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__version(requestOptions));
    }

    private async __version(requestOptions?: OpikApiClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "Comet-Workspace": requestOptions?.workspaceName ?? this._options?.workspaceName,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OpikApiEnvironment.Default,
                "is-alive/ver",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OpikApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/is-alive/ver");
    }
}
