"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OpikApiEnvironment = void 0;
exports.OpikApiEnvironment = {
    Default: "http://localhost:5173/api",
};
