name: Docs - Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/opik-documentation/documentation/**'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git diff

      - name: Install Fern
        run: npm install -g fern-api@0.64.26

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          SEGMENT_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_KEY }}
          GTM_CONTAINER_ID: ${{ secrets.GTM_CONTAINER_ID }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_API_HOST: ${{ secrets.POSTHOG_API_HOST }}
        run: |
          cd apps/opik-documentation/documentation
          fern generate --docs
