name: Installation Tests

on:
  schedule:
    - cron: '0 12 * * *' # runs every day at noon UTC
  workflow_dispatch:

jobs:
  test-readme-installation:
    name: Test Main README.md Installation With Pull
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/tests_end_to_end/test_requirements.txt

      - name: Install via README.md instructions
        run: |
          cd ${{ github.workspace }}/deployment/docker_compose
          docker compose pull
          docker compose up --detach

      - name: Check Docker pods are up (Local)
        run: |
          chmod +x ./tests_end_to_end/installer_utils/check_docker_compose_pods.sh
          ./tests_end_to_end/installer_utils/check_docker_compose_pods.sh
        shell: bash

      - name: Check backend health (Local)
        run: |
          chmod +x ./tests_end_to_end/installer_utils/check_backend.sh
          ./tests_end_to_end/installer_utils/check_backend.sh
        shell: bash

      - name: Run trace test
        run: |
          cd ${{ github.workspace }}/tests_end_to_end
          export PYTHONPATH='.'
          pytest -xvs tests/Installation/test_trace_logging.py

      - name: Stop Opik
        if: always()
        run: |
          cd /tmp/opik-test/deployment/docker-compose
          docker compose down

  test-docs-installation:
    name: Test Comet Documentation Installation No Pull First
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/tests_end_to_end/test_requirements.txt

      - name: Install via Documentation instructions
        run: |
          cd ${{ github.workspace }}/deployment/docker_compose
          docker compose up --detach

      - name: Check Docker pods are up (Local)
        run: |
          chmod +x ./tests_end_to_end/installer_utils/check_docker_compose_pods.sh
          ./tests_end_to_end/installer_utils/check_docker_compose_pods.sh
        shell: bash

      - name: Check backend health (Local)
        run: |
          chmod +x ./tests_end_to_end/installer_utils/check_backend.sh
          ./tests_end_to_end/installer_utils/check_backend.sh
        shell: bash


      - name: Run trace test
        run: |
          cd ${{ github.workspace }}/tests_end_to_end
          export PYTHONPATH='.'
          pytest -xvs tests/Installation/test_trace_logging.py

      - name: Stop Opik
        if: always()
        run: |
          cd opik/deployment/docker-compose
          docker compose down

  test-docker-compose-readme-default:
    name: Test Deployment README Default
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/tests_end_to_end/test_requirements.txt

      - name: Install via Docker Compose README default method
        run: |
          cd ${{ github.workspace }}/deployment/docker-compose
          docker compose pull
          docker compose -f docker-compose.yaml up -d
          
      - name: Check Docker pods are up (Local)
        run: |
          chmod +x ./tests_end_to_end/installer_utils/check_docker_compose_pods.sh
          ./tests_end_to_end/installer_utils/check_docker_compose_pods.sh
        shell: bash

      - name: Check backend health (Local)
        run: |
          chmod +x ./tests_end_to_end/installer_utils/check_backend.sh
          ./tests_end_to_end/installer_utils/check_backend.sh
        shell: bash

      - name: Run trace test
        run: |
          cd ${{ github.workspace }}/tests_end_to_end
          export PYTHONPATH='.'
          pytest -xvs tests/Installation/test_trace_logging.py

      - name: Stop Opik
        if: always()
        run: |
          cd deployment/docker-compose
          docker compose down

  test-docker-compose-readme-specific-version:
    name: Test Deployment README with Specific Version
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/tests_end_to_end/test_requirements.txt

      - name: Install via Docker Compose README with specific version
        run: |
          cd ${{ github.workspace }}/deployment/docker-compose
          export OPIK_VERSION=1.6.5
          docker compose pull
          docker compose -f docker-compose.yaml up -d
          
      - name: Check Docker pods are up (Local)
        run: |
          chmod +x ./tests_end_to_end/installer_utils/check_docker_compose_pods.sh
          ./tests_end_to_end/installer_utils/check_docker_compose_pods.sh
        shell: bash

      - name: Check backend health (Local)
        run: |
          chmod +x ./tests_end_to_end/installer_utils/check_backend.sh
          ./tests_end_to_end/installer_utils/check_backend.sh
        shell: bash

      - name: Run trace test
        run: |
          cd ${{ github.workspace }}/tests_end_to_end
          export PYTHONPATH='.'
          pytest -xvs tests/Installation/test_trace_logging.py

      - name: Stop Opik
        if: always()
        run: |
          cd deployment/docker-compose
          docker compose down

  test-docker-compose-readme-build:
    name: Test Deployment README with Build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/tests_end_to_end/test_requirements.txt

      - name: Install via Docker Compose README with build
        run: |
          cd ${{ github.workspace }}/deployment/docker-compose
          docker compose pull
          docker compose -f docker-compose.yaml up -d --build
          
      - name: Check Docker pods are up (Local)
        run: |
          chmod +x ./tests_end_to_end/installer_utils/check_docker_compose_pods.sh
          ./tests_end_to_end/installer_utils/check_docker_compose_pods.sh
        shell: bash

      - name: Check backend health (Local)
        run: |
          chmod +x ./tests_end_to_end/installer_utils/check_backend.sh
          ./tests_end_to_end/installer_utils/check_backend.sh
        shell: bash

      - name: Run trace test
        run: |
          cd ${{ github.workspace }}/tests_end_to_end
          export PYTHONPATH='.'
          pytest -xvs tests/Installation/test_trace_logging.py

      - name: Stop Opik
        if: always()
        run: |
          cd deployment/docker-compose
          docker compose down
