package com.comet.opik.domain;

import java.util.List;

public class DemoData {

    public static final List<String> PROJECTS = List.of("Demo evaluation", "Demo chatbot 🤖", "Opik Demo Agent Observability", "Opik Demo Assistant");

    public static final List<String> DATASETS = List.of("Demo dataset", "Opik Demo Questions");

    public static final List<String> EXPERIMENTS = List.of(
            "Demo evaluation",
            "Demo-opik-assistant-v2",
            "Demo-opik-assistant-v1",

            "Demo-forward_tamarind_3921",
            "Demo-colorful_cobbler_5082",
            "Demo-profound_grouse_5114",
            "Demo-normal_toucan_3742",
            "Demo-flexible_tundra_8981",
            "Demo-specified_resin_1121",
            "Demo-coral_chateau_1249",
            "Demo-major_fruit_6938",
            "Demo-flat_bulb_3765",
            "Demo-horizontal_shrimp_833",
            "Demo-continuous_milk_2919",

            "Demo-elegant_barnacle_1886",
            "Demo-major_lynx_5841",
            "Demo-integrated_flitch_6452",
            "Demo-gleaming_east_5121",
            "Demo-useful_scaffold_290",
            "Demo-mammoth_valley_5352",
            "Demo-back_raccoon_7126",
            "Demo-clinical_reindeer_8703",
            "Demo-realistic_dog_4966",
            "Demo-gleaming_swift_8751",
            "Demo-large_cabana_4241",
            "Demo-quickest_walrus_2906",
            "Demo-managing_banana_4567",
            "Demo-functional_anaconda_7031",
            "Demo-vertical_worm_6616",
            "Demo-lazy_carp_1608",
            "Demo-competent_barracuda_4210",
            "Demo-impressive_cake_7656",
            "Demo-serious_pilaster_6785",
            "Demo-early_taper_7121",
            "Demo-associated_mayo_4206",
            "Demo-objective_horse_6059",
            "Demo-liquid_gazelle_9339",
            "Demo-outrageous_valley_1908",
            "Demo-temporary_amphibian_1318",
            "Demo-complete_burl_6649",
            "Demo-additional_shark_7824",
            "Demo-alternative_plum_2442",
            "Demo-crucial_caviar_4845",
            "Demo-civil_nailer_8764",
            "Demo-zealous_embassy_2308",
            "Demo-absolute_kumquat_2632",
            "Demo-compact_unicorn_77",
            "Demo-smoggy_sandstone_8048",
            "Demo-mean_nectarine_7055",
            "Demo-itchy_newel_2661",
            "Demo-rolling_frieze_7194",
            "Demo-estimated_kerf_6365",
            "Demo-secure_shrew_6436",
            "Demo-practical_syrup_4323",
            "Demo-consistent_dividend_1768",
            "Demo-striking_bracket_7404",
            "Demo-assistant_thorn_2023",
            "Demo-rational_tangerine_8921",
            "Demo-constitutional_pinniped_2901",
            "Demo-gradual_equator_2628",
            "Demo-ambitious_angelfish_1399",
            "Demo-passive_syrup_5218",
            "Demo-expected_rambutan_2917",
            "Demo-ancient_orangutan_9523",
            "Demo-defensive_nectar_6276",
            "Demo-selective_noodle_9953",
            "Demo-following_bean_1403",
            "Demo-uncertain_quince_2622",
            "Demo-striped_lemming_7162",
            "Demo-full_ox_5955",
            "Demo-explicit_baboon_831",
            "Demo-free_trim_9182",
            "Demo-smoggy_nut_3087",
            "Demo-crowded_crane_3968",
            "Demo-lazy_raclette_9596",
            "Demo-amateur_compass_58",
            "Demo-striped_notch_3239",
            "Demo-bored_satsuma_8915"
    );
}
