import React, { ReactNode, useMemo } from "react";
import { PermissionsProvider as BasePermissionsProvider } from "@/contexts/PermissionsContext";
import useUserPermission from "./useUserPermission";
import { PermissionsContextValue } from "@/types/permissions";

const PermissionsProvider: React.FC<{ children: ReactNode }> = ({
  children,
}) => {
  const {
    canViewExperiments,
    canCreateExperiments,
    canViewDashboards,
    canCreateDashboards,
    canEditDashboards,
    canDeleteDashboards,
    canViewDatasets,
    canCreateDatasets,
    canEditDatasets,
    canDeleteDatasets,
    canCreateProjects,
    canDeleteProjects,
    canCreateAnnotationQueues,
    canEditAnnotationQueues,
    canDeleteAnnotationQueues,
    canDeleteTraces,
    canViewPrompts,
    canCreatePrompts,
    canEditPrompts,
    canDeletePrompts,
    canDeleteOptimizationRuns,
    canConfigureWorkspaceSettings,
    canUpdateAIProviders,
    canViewOnlineEvaluationRules,
    canUpdateOnlineEvaluationRules,
    canViewAlerts,
    canUpdateAlerts,
    canAnnotateTraceSpanThread,
    canLogTraceSpanThread,
    canUsePlayground,
    canViewAgentPlayground,
    canUseOptimizationStudio,
    canViewOptimizationRuns,
    isPending,
  } = useUserPermission();

  const value: PermissionsContextValue = useMemo(
    () => ({
      permissions: {
        canViewExperiments,
        canCreateExperiments,
        canViewDashboards,
        canCreateDashboards,
        canEditDashboards,
        canDeleteDashboards,
        canViewDatasets,
        canCreateDatasets,
        canEditDatasets,
        canDeleteDatasets,
        canCreateProjects,
        canDeleteProjects,
        canCreateAnnotationQueues,
        canEditAnnotationQueues,
        canDeleteAnnotationQueues,
        canDeleteTraces,
        canViewPrompts,
        canCreatePrompts,
        canEditPrompts,
        canDeletePrompts,
        canDeleteOptimizationRuns,
        canConfigureWorkspaceSettings,
        canUpdateAIProviders,
        canViewOnlineEvaluationRules,
        canUpdateOnlineEvaluationRules,
        canViewAlerts,
        canUpdateAlerts,
        canAnnotateTraceSpanThread,
        canLogTraceSpanThread,
        canUsePlayground,
        canViewAgentPlayground,
        canUseOptimizationStudio,
        canViewOptimizationRuns,
      },
      isPending,
    }),
    [
      canViewExperiments,
      canCreateExperiments,
      canViewDashboards,
      canCreateDashboards,
      canEditDashboards,
      canDeleteDashboards,
      canViewDatasets,
      canCreateDatasets,
      canEditDatasets,
      canDeleteDatasets,
      canCreateProjects,
      canDeleteProjects,
      canCreateAnnotationQueues,
      canEditAnnotationQueues,
      canDeleteAnnotationQueues,
      canDeleteTraces,
      canViewPrompts,
      canCreatePrompts,
      canEditPrompts,
      canDeletePrompts,
      canDeleteOptimizationRuns,
      canConfigureWorkspaceSettings,
      canUpdateAIProviders,
      canViewOnlineEvaluationRules,
      canUpdateOnlineEvaluationRules,
      canViewAlerts,
      canUpdateAlerts,
      canAnnotateTraceSpanThread,
      canLogTraceSpanThread,
      canUsePlayground,
      canViewAgentPlayground,
      canUseOptimizationStudio,
      canViewOptimizationRuns,
      isPending,
    ],
  );

  return (
    <BasePermissionsProvider value={value}>{children}</BasePermissionsProvider>
  );
};

export default PermissionsProvider;
